// automatically generated by the FlatBuffers compiler, do not modify

package vn.com.vng.gsmobile.casino.flatbuffers;

public final class AchievementType {
  private AchievementType() { }
  public static final byte Normal = 0;
  public static final byte LikeFacebook = 1;
  public static final byte ShareFacebook = 2;
  public static final byte InviteFacebook = 3;
  public static final byte WinGame = 4;
  public static final byte AbsoluteWinGame = 5;
  public static final byte BuyItem = 6;
  public static final byte BuyCoin = 7;

  public static final String[] names = { "Normal", "LikeFacebook", "ShareFacebook", "InviteFacebook", "WinGame", "AbsoluteWinGame", "BuyItem", "BuyCoin", };

  public static String name(int e) { return names[e]; }
}

