// automatically generated by the FlatBuffers compiler, do not modify

package vn.com.vng.gsmobile.casino.flatbuffers;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class Card3LaInfo extends Table {
  public static Card3LaInfo getRootAsCard3LaInfo(ByteBuffer _bb) { return getRootAsCard3LaInfo(_bb, new Card3LaInfo()); }
  public static Card3LaInfo getRootAsCard3LaInfo(ByteBuffer _bb, Card3LaInfo obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public Card3LaInfo __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public int cardId() { int o = __offset(4); return o != 0 ? bb.get(o + bb_pos) & 0xFF : 0; }
  public boolean mutateCardId(int card_id) { int o = __offset(4); if (o != 0) { bb.put(o + bb_pos, (byte)card_id); return true; } else { return false; } }
  public int showFlag() { int o = __offset(6); return o != 0 ? bb.get(o + bb_pos) & 0xFF : 0; }
  public boolean mutateShowFlag(int show_flag) { int o = __offset(6); if (o != 0) { bb.put(o + bb_pos, (byte)show_flag); return true; } else { return false; } }

  public static int createCard3LaInfo(FlatBufferBuilder builder,
      int card_id,
      int show_flag) {
    builder.startObject(2);
    Card3LaInfo.addShowFlag(builder, show_flag);
    Card3LaInfo.addCardId(builder, card_id);
    return Card3LaInfo.endCard3LaInfo(builder);
  }

  public static void startCard3LaInfo(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addCardId(FlatBufferBuilder builder, int cardId) { builder.addByte(0, (byte)cardId, 0); }
  public static void addShowFlag(FlatBufferBuilder builder, int showFlag) { builder.addByte(1, (byte)showFlag, 0); }
  public static int endCard3LaInfo(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

