// automatically generated by the FlatBuffers compiler, do not modify

package vn.com.vng.gsmobile.casino.flatbuffers;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class CardTLMNInfo extends Table {
  public static CardTLMNInfo getRootAsCardTLMNInfo(ByteBuffer _bb) { return getRootAsCardTLMNInfo(_bb, new CardTLMNInfo()); }
  public static CardTLMNInfo getRootAsCardTLMNInfo(ByteBuffer _bb, CardTLMNInfo obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public CardTLMNInfo __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public int cardId() { int o = __offset(4); return o != 0 ? bb.get(o + bb_pos) & 0xFF : 0; }
  public boolean mutateCardId(int card_id) { int o = __offset(4); if (o != 0) { bb.put(o + bb_pos, (byte)card_id); return true; } else { return false; } }
  public int turnIdx() { int o = __offset(6); return o != 0 ? bb.get(o + bb_pos) & 0xFF : 0; }
  public boolean mutateTurnIdx(int turn_idx) { int o = __offset(6); if (o != 0) { bb.put(o + bb_pos, (byte)turn_idx); return true; } else { return false; } }
  public int ringIdx() { int o = __offset(8); return o != 0 ? bb.get(o + bb_pos) & 0xFF : 0; }
  public boolean mutateRingIdx(int ring_idx) { int o = __offset(8); if (o != 0) { bb.put(o + bb_pos, (byte)ring_idx); return true; } else { return false; } }

  public static int createCardTLMNInfo(FlatBufferBuilder builder,
      int card_id,
      int turn_idx,
      int ring_idx) {
    builder.startObject(3);
    CardTLMNInfo.addRingIdx(builder, ring_idx);
    CardTLMNInfo.addTurnIdx(builder, turn_idx);
    CardTLMNInfo.addCardId(builder, card_id);
    return CardTLMNInfo.endCardTLMNInfo(builder);
  }

  public static void startCardTLMNInfo(FlatBufferBuilder builder) { builder.startObject(3); }
  public static void addCardId(FlatBufferBuilder builder, int cardId) { builder.addByte(0, (byte)cardId, 0); }
  public static void addTurnIdx(FlatBufferBuilder builder, int turnIdx) { builder.addByte(1, (byte)turnIdx, 0); }
  public static void addRingIdx(FlatBufferBuilder builder, int ringIdx) { builder.addByte(2, (byte)ringIdx, 0); }
  public static int endCardTLMNInfo(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

