// automatically generated by the FlatBuffers compiler, do not modify

package vn.com.vng.gsmobile.casino.flatbuffers;

public final class CardClass {
  private CardClass() { }
  public static final byte Card_None = -1;
  public static final byte Card_A = 0;
  public static final byte Card_B = 1;
  public static final byte Card_C = 2;
  public static final byte Card_D = 3;

  public static final String[] names = { "Card_None", "Card_A", "Card_B", "Card_C", "Card_D", };

  public static String name(int e) { return names[e - Card_None]; }
}

