// automatically generated by the FlatBuffers compiler, do not modify

package vn.com.vng.gsmobile.casino.flatbuffers;

public final class CardValue {
  private CardValue() { }
  public static final byte Card_None = -1;
  public static final byte Card_3 = 0;
  public static final byte Card_4 = 1;
  public static final byte Card_5 = 2;
  public static final byte Card_6 = 3;
  public static final byte Card_7 = 4;
  public static final byte Card_8 = 5;
  public static final byte Card_9 = 6;
  public static final byte Card_10 = 7;
  public static final byte Card_J = 8;
  public static final byte Card_Q = 9;
  public static final byte Card_K = 10;
  public static final byte Card_A = 11;
  public static final byte Card_2 = 12;

  public static final String[] names = { "Card_None", "Card_3", "Card_4", "Card_5", "Card_6", "Card_7", "Card_8", "Card_9", "Card_10", "Card_J", "Card_Q", "Card_K", "Card_A", "Card_2", };

  public static String name(int e) { return names[e - Card_None]; }
}

