// automatically generated by the FlatBuffers compiler, do not modify

package vn.com.vng.gsmobile.casino.flatbuffers;

public final class CardID {
  private CardID() { }
  public static final byte Card_None = 0;
  public static final byte Card_3_A = 1;
  public static final byte Card_3_B = 2;
  public static final byte Card_3_C = 3;
  public static final byte Card_3_D = 4;
  public static final byte Card_4_A = 5;
  public static final byte Card_4_B = 6;
  public static final byte Card_4_C = 7;
  public static final byte Card_4_D = 8;
  public static final byte Card_5_A = 9;
  public static final byte Card_5_B = 10;
  public static final byte Card_5_C = 11;
  public static final byte Card_5_D = 12;
  public static final byte Card_6_A = 13;
  public static final byte Card_6_B = 14;
  public static final byte Card_6_C = 15;
  public static final byte Card_6_D = 16;
  public static final byte Card_7_A = 17;
  public static final byte Card_7_B = 18;
  public static final byte Card_7_C = 19;
  public static final byte Card_7_D = 20;
  public static final byte Card_8_A = 21;
  public static final byte Card_8_B = 22;
  public static final byte Card_8_C = 23;
  public static final byte Card_8_D = 24;
  public static final byte Card_9_A = 25;
  public static final byte Card_9_B = 26;
  public static final byte Card_9_C = 27;
  public static final byte Card_9_D = 28;
  public static final byte Card_10_A = 29;
  public static final byte Card_10_B = 30;
  public static final byte Card_10_C = 31;
  public static final byte Card_10_D = 32;
  public static final byte Card_J_A = 33;
  public static final byte Card_J_B = 34;
  public static final byte Card_J_C = 35;
  public static final byte Card_J_D = 36;
  public static final byte Card_Q_A = 37;
  public static final byte Card_Q_B = 38;
  public static final byte Card_Q_C = 39;
  public static final byte Card_Q_D = 40;
  public static final byte Card_K_A = 41;
  public static final byte Card_K_B = 42;
  public static final byte Card_K_C = 43;
  public static final byte Card_K_D = 44;
  public static final byte Card_A_A = 45;
  public static final byte Card_A_B = 46;
  public static final byte Card_A_C = 47;
  public static final byte Card_A_D = 48;
  public static final byte Card_2_A = 49;
  public static final byte Card_2_B = 50;
  public static final byte Card_2_C = 51;
  public static final byte Card_2_D = 52;
  public static final byte Card_Hide = 127;

  public static final String[] names = { "Card_None", "Card_3_A", "Card_3_B", "Card_3_C", "Card_3_D", "Card_4_A", "Card_4_B", "Card_4_C", "Card_4_D", "Card_5_A", "Card_5_B", "Card_5_C", "Card_5_D", "Card_6_A", "Card_6_B", "Card_6_C", "Card_6_D", "Card_7_A", "Card_7_B", "Card_7_C", "Card_7_D", "Card_8_A", "Card_8_B", "Card_8_C", "Card_8_D", "Card_9_A", "Card_9_B", "Card_9_C", "Card_9_D", "Card_10_A", "Card_10_B", "Card_10_C", "Card_10_D", "Card_J_A", "Card_J_B", "Card_J_C", "Card_J_D", "Card_Q_A", "Card_Q_B", "Card_Q_C", "Card_Q_D", "Card_K_A", "Card_K_B", "Card_K_C", "Card_K_D", "Card_A_A", "Card_A_B", "Card_A_C", "Card_A_D", "Card_2_A", "Card_2_B", "Card_2_C", "Card_2_D", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "Card_Hide", };

  public static String name(int e) { return names[e]; }
}

