// automatically generated by the FlatBuffers compiler, do not modify

package vn.com.vng.gsmobile.casino.flatbuffers;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class ChatMsgRoom extends Table {
  public static ChatMsgRoom getRootAsChatMsgRoom(ByteBuffer _bb) { return getRootAsChatMsgRoom(_bb, new ChatMsgRoom()); }
  public static ChatMsgRoom getRootAsChatMsgRoom(ByteBuffer _bb, ChatMsgRoom obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public ChatMsgRoom __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public String msg() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer msgAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public long fromUid() { int o = __offset(6); return o != 0 ? bb.getLong(o + bb_pos) : 0; }
  public boolean mutateFromUid(long from_uid) { int o = __offset(6); if (o != 0) { bb.putLong(o + bb_pos, from_uid); return true; } else { return false; } }
  public String fromName() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer fromNameAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public long roomId() { int o = __offset(10); return o != 0 ? bb.getLong(o + bb_pos) : 0; }
  public boolean mutateRoomId(long room_id) { int o = __offset(10); if (o != 0) { bb.putLong(o + bb_pos, room_id); return true; } else { return false; } }

  public static int createChatMsgRoom(FlatBufferBuilder builder,
      int msgOffset,
      long from_uid,
      int from_nameOffset,
      long room_id) {
    builder.startObject(4);
    ChatMsgRoom.addRoomId(builder, room_id);
    ChatMsgRoom.addFromUid(builder, from_uid);
    ChatMsgRoom.addFromName(builder, from_nameOffset);
    ChatMsgRoom.addMsg(builder, msgOffset);
    return ChatMsgRoom.endChatMsgRoom(builder);
  }

  public static void startChatMsgRoom(FlatBufferBuilder builder) { builder.startObject(4); }
  public static void addMsg(FlatBufferBuilder builder, int msgOffset) { builder.addOffset(0, msgOffset, 0); }
  public static void addFromUid(FlatBufferBuilder builder, long fromUid) { builder.addLong(1, fromUid, 0); }
  public static void addFromName(FlatBufferBuilder builder, int fromNameOffset) { builder.addOffset(2, fromNameOffset, 0); }
  public static void addRoomId(FlatBufferBuilder builder, long roomId) { builder.addLong(3, roomId, 0); }
  public static int endChatMsgRoom(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

