// automatically generated by the FlatBuffers compiler, do not modify

package vn.com.vng.gsmobile.casino.flatbuffers;

public final class ClientOS {
  private ClientOS() { }
  public static final byte OS_Unknown = 0;
  public static final byte OS_IOS = 1;
  public static final byte OS_Android = 2;

  public static final String[] names = { "OS_Unknown", "OS_IOS", "OS_Android", };

  public static String name(int e) { return names[e]; }
}

