// automatically generated by the FlatBuffers compiler, do not modify

package vn.com.vng.gsmobile.casino.flatbuffers;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class CMDDeleteMail extends Table {
  public static CMDDeleteMail getRootAsCMDDeleteMail(ByteBuffer _bb) { return getRootAsCMDDeleteMail(_bb, new CMDDeleteMail()); }
  public static CMDDeleteMail getRootAsCMDDeleteMail(ByteBuffer _bb, CMDDeleteMail obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public CMDDeleteMail __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public long uid() { int o = __offset(4); return o != 0 ? bb.getLong(o + bb_pos) : 0; }
  public boolean mutateUid(long uid) { int o = __offset(4); if (o != 0) { bb.putLong(o + bb_pos, uid); return true; } else { return false; } }
  public String id() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer idAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public int mailType() { int o = __offset(8); return o != 0 ? bb.get(o + bb_pos) & 0xFF : 0; }
  public boolean mutateMailType(int mail_type) { int o = __offset(8); if (o != 0) { bb.put(o + bb_pos, (byte)mail_type); return true; } else { return false; } }

  public static int createCMDDeleteMail(FlatBufferBuilder builder,
      long uid,
      int idOffset,
      int mail_type) {
    builder.startObject(3);
    CMDDeleteMail.addUid(builder, uid);
    CMDDeleteMail.addId(builder, idOffset);
    CMDDeleteMail.addMailType(builder, mail_type);
    return CMDDeleteMail.endCMDDeleteMail(builder);
  }

  public static void startCMDDeleteMail(FlatBufferBuilder builder) { builder.startObject(3); }
  public static void addUid(FlatBufferBuilder builder, long uid) { builder.addLong(0, uid, 0); }
  public static void addId(FlatBufferBuilder builder, int idOffset) { builder.addOffset(1, idOffset, 0); }
  public static void addMailType(FlatBufferBuilder builder, int mailType) { builder.addByte(2, (byte)mailType, 0); }
  public static int endCMDDeleteMail(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

