// automatically generated by the FlatBuffers compiler, do not modify

package vn.com.vng.gsmobile.casino.flatbuffers;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class CMDGetGameStatus extends Table {
  public static CMDGetGameStatus getRootAsCMDGetGameStatus(ByteBuffer _bb) { return getRootAsCMDGetGameStatus(_bb, new CMDGetGameStatus()); }
  public static CMDGetGameStatus getRootAsCMDGetGameStatus(ByteBuffer _bb, CMDGetGameStatus obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public CMDGetGameStatus __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public long roomId() { int o = __offset(4); return o != 0 ? bb.getLong(o + bb_pos) : 0; }
  public boolean mutateRoomId(long room_id) { int o = __offset(4); if (o != 0) { bb.putLong(o + bb_pos, room_id); return true; } else { return false; } }
  public int gameType() { int o = __offset(6); return o != 0 ? bb.get(o + bb_pos) & 0xFF : 0; }
  public boolean mutateGameType(int game_type) { int o = __offset(6); if (o != 0) { bb.put(o + bb_pos, (byte)game_type); return true; } else { return false; } }

  public static int createCMDGetGameStatus(FlatBufferBuilder builder,
      long room_id,
      int game_type) {
    builder.startObject(2);
    CMDGetGameStatus.addRoomId(builder, room_id);
    CMDGetGameStatus.addGameType(builder, game_type);
    return CMDGetGameStatus.endCMDGetGameStatus(builder);
  }

  public static void startCMDGetGameStatus(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addRoomId(FlatBufferBuilder builder, long roomId) { builder.addLong(0, roomId, 0); }
  public static void addGameType(FlatBufferBuilder builder, int gameType) { builder.addByte(1, (byte)gameType, 0); }
  public static int endCMDGetGameStatus(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

