// automatically generated by the FlatBuffers compiler, do not modify

package vn.com.vng.gsmobile.casino.flatbuffers;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class CMDGetInfoFromSocial extends Table {
  public static CMDGetInfoFromSocial getRootAsCMDGetInfoFromSocial(ByteBuffer _bb) { return getRootAsCMDGetInfoFromSocial(_bb, new CMDGetInfoFromSocial()); }
  public static CMDGetInfoFromSocial getRootAsCMDGetInfoFromSocial(ByteBuffer _bb, CMDGetInfoFromSocial obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public CMDGetInfoFromSocial __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public String sidList(int j) { int o = __offset(4); return o != 0 ? __string(__vector(o) + j * 4) : null; }
  public int sidListLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }
  public UserInfo userList(int j) { return userList(new UserInfo(), j); }
  public UserInfo userList(UserInfo obj, int j) { int o = __offset(6); return o != 0 ? obj.__init(__indirect(__vector(o) + j * 4), bb) : null; }
  public int userListLength() { int o = __offset(6); return o != 0 ? __vector_len(o) : 0; }

  public static int createCMDGetInfoFromSocial(FlatBufferBuilder builder,
      int sid_listOffset,
      int user_listOffset) {
    builder.startObject(2);
    CMDGetInfoFromSocial.addUserList(builder, user_listOffset);
    CMDGetInfoFromSocial.addSidList(builder, sid_listOffset);
    return CMDGetInfoFromSocial.endCMDGetInfoFromSocial(builder);
  }

  public static void startCMDGetInfoFromSocial(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addSidList(FlatBufferBuilder builder, int sidListOffset) { builder.addOffset(0, sidListOffset, 0); }
  public static int createSidListVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startSidListVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addUserList(FlatBufferBuilder builder, int userListOffset) { builder.addOffset(1, userListOffset, 0); }
  public static int createUserListVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startUserListVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endCMDGetInfoFromSocial(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

