// automatically generated by the FlatBuffers compiler, do not modify

package vn.com.vng.gsmobile.casino.flatbuffers;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class CMDGetFullMailMess extends Table {
  public static CMDGetFullMailMess getRootAsCMDGetFullMailMess(ByteBuffer _bb) { return getRootAsCMDGetFullMailMess(_bb, new CMDGetFullMailMess()); }
  public static CMDGetFullMailMess getRootAsCMDGetFullMailMess(ByteBuffer _bb, CMDGetFullMailMess obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public CMDGetFullMailMess __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public long uid() { int o = __offset(4); return o != 0 ? bb.getLong(o + bb_pos) : 0; }
  public boolean mutateUid(long uid) { int o = __offset(4); if (o != 0) { bb.putLong(o + bb_pos, uid); return true; } else { return false; } }
  public String mailId() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer mailIdAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public String fullMess() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer fullMessAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public int mailType() { int o = __offset(10); return o != 0 ? bb.get(o + bb_pos) & 0xFF : 0; }
  public boolean mutateMailType(int mail_type) { int o = __offset(10); if (o != 0) { bb.put(o + bb_pos, (byte)mail_type); return true; } else { return false; } }

  public static int createCMDGetFullMailMess(FlatBufferBuilder builder,
      long uid,
      int mail_idOffset,
      int full_messOffset,
      int mail_type) {
    builder.startObject(4);
    CMDGetFullMailMess.addUid(builder, uid);
    CMDGetFullMailMess.addFullMess(builder, full_messOffset);
    CMDGetFullMailMess.addMailId(builder, mail_idOffset);
    CMDGetFullMailMess.addMailType(builder, mail_type);
    return CMDGetFullMailMess.endCMDGetFullMailMess(builder);
  }

  public static void startCMDGetFullMailMess(FlatBufferBuilder builder) { builder.startObject(4); }
  public static void addUid(FlatBufferBuilder builder, long uid) { builder.addLong(0, uid, 0); }
  public static void addMailId(FlatBufferBuilder builder, int mailIdOffset) { builder.addOffset(1, mailIdOffset, 0); }
  public static void addFullMess(FlatBufferBuilder builder, int fullMessOffset) { builder.addOffset(2, fullMessOffset, 0); }
  public static void addMailType(FlatBufferBuilder builder, int mailType) { builder.addByte(3, (byte)mailType, 0); }
  public static int endCMDGetFullMailMess(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

