// automatically generated by the FlatBuffers compiler, do not modify

package vn.com.vng.gsmobile.casino.flatbuffers;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class CMDGetGiftList extends Table {
  public static CMDGetGiftList getRootAsCMDGetGiftList(ByteBuffer _bb) { return getRootAsCMDGetGiftList(_bb, new CMDGetGiftList()); }
  public static CMDGetGiftList getRootAsCMDGetGiftList(ByteBuffer _bb, CMDGetGiftList obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public CMDGetGiftList __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public long uid() { int o = __offset(4); return o != 0 ? bb.getLong(o + bb_pos) : 0; }
  public boolean mutateUid(long uid) { int o = __offset(4); if (o != 0) { bb.putLong(o + bb_pos, uid); return true; } else { return false; } }
  public GiftItem giftDaily(int j) { return giftDaily(new GiftItem(), j); }
  public GiftItem giftDaily(GiftItem obj, int j) { int o = __offset(6); return o != 0 ? obj.__init(__indirect(__vector(o) + j * 4), bb) : null; }
  public int giftDailyLength() { int o = __offset(6); return o != 0 ? __vector_len(o) : 0; }
  public int giftDailyDay() { int o = __offset(8); return o != 0 ? bb.get(o + bb_pos) & 0xFF : 0; }
  public boolean mutateGiftDailyDay(int gift_daily_day) { int o = __offset(8); if (o != 0) { bb.put(o + bb_pos, (byte)gift_daily_day); return true; } else { return false; } }
  public int giftDailyState(int j) { int o = __offset(10); return o != 0 ? bb.get(__vector(o) + j * 1) & 0xFF : 0; }
  public int giftDailyStateLength() { int o = __offset(10); return o != 0 ? __vector_len(o) : 0; }
  public ByteBuffer giftDailyStateAsByteBuffer() { return __vector_as_bytebuffer(10, 1); }
  public boolean mutateGiftDailyState(int j, int gift_daily_state) { int o = __offset(10); if (o != 0) { bb.put(__vector(o) + j * 1, (byte)gift_daily_state); return true; } else { return false; } }
  public GiftItem giftVip(int j) { return giftVip(new GiftItem(), j); }
  public GiftItem giftVip(GiftItem obj, int j) { int o = __offset(12); return o != 0 ? obj.__init(__indirect(__vector(o) + j * 4), bb) : null; }
  public int giftVipLength() { int o = __offset(12); return o != 0 ? __vector_len(o) : 0; }
  public int giftVipDay() { int o = __offset(14); return o != 0 ? bb.get(o + bb_pos) & 0xFF : 0; }
  public boolean mutateGiftVipDay(int gift_vip_day) { int o = __offset(14); if (o != 0) { bb.put(o + bb_pos, (byte)gift_vip_day); return true; } else { return false; } }
  public GiftItem giftSystem(int j) { return giftSystem(new GiftItem(), j); }
  public GiftItem giftSystem(GiftItem obj, int j) { int o = __offset(16); return o != 0 ? obj.__init(__indirect(__vector(o) + j * 4), bb) : null; }
  public int giftSystemLength() { int o = __offset(16); return o != 0 ? __vector_len(o) : 0; }

  public static int createCMDGetGiftList(FlatBufferBuilder builder,
      long uid,
      int gift_dailyOffset,
      int gift_daily_day,
      int gift_daily_stateOffset,
      int gift_vipOffset,
      int gift_vip_day,
      int gift_systemOffset) {
    builder.startObject(7);
    CMDGetGiftList.addUid(builder, uid);
    CMDGetGiftList.addGiftSystem(builder, gift_systemOffset);
    CMDGetGiftList.addGiftVip(builder, gift_vipOffset);
    CMDGetGiftList.addGiftDailyState(builder, gift_daily_stateOffset);
    CMDGetGiftList.addGiftDaily(builder, gift_dailyOffset);
    CMDGetGiftList.addGiftVipDay(builder, gift_vip_day);
    CMDGetGiftList.addGiftDailyDay(builder, gift_daily_day);
    return CMDGetGiftList.endCMDGetGiftList(builder);
  }

  public static void startCMDGetGiftList(FlatBufferBuilder builder) { builder.startObject(7); }
  public static void addUid(FlatBufferBuilder builder, long uid) { builder.addLong(0, uid, 0); }
  public static void addGiftDaily(FlatBufferBuilder builder, int giftDailyOffset) { builder.addOffset(1, giftDailyOffset, 0); }
  public static int createGiftDailyVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startGiftDailyVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addGiftDailyDay(FlatBufferBuilder builder, int giftDailyDay) { builder.addByte(2, (byte)giftDailyDay, 0); }
  public static void addGiftDailyState(FlatBufferBuilder builder, int giftDailyStateOffset) { builder.addOffset(3, giftDailyStateOffset, 0); }
  public static int createGiftDailyStateVector(FlatBufferBuilder builder, byte[] data) { builder.startVector(1, data.length, 1); for (int i = data.length - 1; i >= 0; i--) builder.addByte(data[i]); return builder.endVector(); }
  public static void startGiftDailyStateVector(FlatBufferBuilder builder, int numElems) { builder.startVector(1, numElems, 1); }
  public static void addGiftVip(FlatBufferBuilder builder, int giftVipOffset) { builder.addOffset(4, giftVipOffset, 0); }
  public static int createGiftVipVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startGiftVipVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addGiftVipDay(FlatBufferBuilder builder, int giftVipDay) { builder.addByte(5, (byte)giftVipDay, 0); }
  public static void addGiftSystem(FlatBufferBuilder builder, int giftSystemOffset) { builder.addOffset(6, giftSystemOffset, 0); }
  public static int createGiftSystemVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startGiftSystemVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endCMDGetGiftList(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

