// automatically generated by the FlatBuffers compiler, do not modify

package vn.com.vng.gsmobile.casino.flatbuffers;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class CMDGameNotice extends Table {
  public static CMDGameNotice getRootAsCMDGameNotice(ByteBuffer _bb) { return getRootAsCMDGameNotice(_bb, new CMDGameNotice()); }
  public static CMDGameNotice getRootAsCMDGameNotice(ByteBuffer _bb, CMDGameNotice obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public CMDGameNotice __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public int gameType() { int o = __offset(4); return o != 0 ? bb.get(o + bb_pos) & 0xFF : 0; }
  public boolean mutateGameType(int game_type) { int o = __offset(4); if (o != 0) { bb.put(o + bb_pos, (byte)game_type); return true; } else { return false; } }
  public String noticeList(int j) { int o = __offset(6); return o != 0 ? __string(__vector(o) + j * 4) : null; }
  public int noticeListLength() { int o = __offset(6); return o != 0 ? __vector_len(o) : 0; }

  public static int createCMDGameNotice(FlatBufferBuilder builder,
      int game_type,
      int notice_listOffset) {
    builder.startObject(2);
    CMDGameNotice.addNoticeList(builder, notice_listOffset);
    CMDGameNotice.addGameType(builder, game_type);
    return CMDGameNotice.endCMDGameNotice(builder);
  }

  public static void startCMDGameNotice(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addGameType(FlatBufferBuilder builder, int gameType) { builder.addByte(0, (byte)gameType, 0); }
  public static void addNoticeList(FlatBufferBuilder builder, int noticeListOffset) { builder.addOffset(1, noticeListOffset, 0); }
  public static int createNoticeListVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startNoticeListVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endCMDGameNotice(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

