// automatically generated by the FlatBuffers compiler, do not modify

package vn.com.vng.gsmobile.casino.flatbuffers;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class CMDGetMailList extends Table {
  public static CMDGetMailList getRootAsCMDGetMailList(ByteBuffer _bb) { return getRootAsCMDGetMailList(_bb, new CMDGetMailList()); }
  public static CMDGetMailList getRootAsCMDGetMailList(ByteBuffer _bb, CMDGetMailList obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public CMDGetMailList __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public long uid() { int o = __offset(4); return o != 0 ? bb.getLong(o + bb_pos) : 0; }
  public boolean mutateUid(long uid) { int o = __offset(4); if (o != 0) { bb.putLong(o + bb_pos, uid); return true; } else { return false; } }
  public MailInfo listMail(int j) { return listMail(new MailInfo(), j); }
  public MailInfo listMail(MailInfo obj, int j) { int o = __offset(6); return o != 0 ? obj.__init(__indirect(__vector(o) + j * 4), bb) : null; }
  public int listMailLength() { int o = __offset(6); return o != 0 ? __vector_len(o) : 0; }

  public static int createCMDGetMailList(FlatBufferBuilder builder,
      long uid,
      int list_mailOffset) {
    builder.startObject(2);
    CMDGetMailList.addUid(builder, uid);
    CMDGetMailList.addListMail(builder, list_mailOffset);
    return CMDGetMailList.endCMDGetMailList(builder);
  }

  public static void startCMDGetMailList(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addUid(FlatBufferBuilder builder, long uid) { builder.addLong(0, uid, 0); }
  public static void addListMail(FlatBufferBuilder builder, int listMailOffset) { builder.addOffset(1, listMailOffset, 0); }
  public static int createListMailVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startListMailVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endCMDGetMailList(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

