// automatically generated by the FlatBuffers compiler, do not modify

package vn.com.vng.gsmobile.casino.flatbuffers;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class CMDGetGiftListSystem extends Table {
  public static CMDGetGiftListSystem getRootAsCMDGetGiftListSystem(ByteBuffer _bb) { return getRootAsCMDGetGiftListSystem(_bb, new CMDGetGiftListSystem()); }
  public static CMDGetGiftListSystem getRootAsCMDGetGiftListSystem(ByteBuffer _bb, CMDGetGiftListSystem obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public CMDGetGiftListSystem __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public long uid() { int o = __offset(4); return o != 0 ? bb.getLong(o + bb_pos) : 0; }
  public boolean mutateUid(long uid) { int o = __offset(4); if (o != 0) { bb.putLong(o + bb_pos, uid); return true; } else { return false; } }
  public GiftItem giftSystem(int j) { return giftSystem(new GiftItem(), j); }
  public GiftItem giftSystem(GiftItem obj, int j) { int o = __offset(6); return o != 0 ? obj.__init(__indirect(__vector(o) + j * 4), bb) : null; }
  public int giftSystemLength() { int o = __offset(6); return o != 0 ? __vector_len(o) : 0; }

  public static int createCMDGetGiftListSystem(FlatBufferBuilder builder,
      long uid,
      int gift_systemOffset) {
    builder.startObject(2);
    CMDGetGiftListSystem.addUid(builder, uid);
    CMDGetGiftListSystem.addGiftSystem(builder, gift_systemOffset);
    return CMDGetGiftListSystem.endCMDGetGiftListSystem(builder);
  }

  public static void startCMDGetGiftListSystem(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addUid(FlatBufferBuilder builder, long uid) { builder.addLong(0, uid, 0); }
  public static void addGiftSystem(FlatBufferBuilder builder, int giftSystemOffset) { builder.addOffset(1, giftSystemOffset, 0); }
  public static int createGiftSystemVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startGiftSystemVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endCMDGetGiftListSystem(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

