// automatically generated by the FlatBuffers compiler, do not modify

package vn.com.vng.gsmobile.casino.flatbuffers;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class CMDGetShopHistory extends Table {
  public static CMDGetShopHistory getRootAsCMDGetShopHistory(ByteBuffer _bb) { return getRootAsCMDGetShopHistory(_bb, new CMDGetShopHistory()); }
  public static CMDGetShopHistory getRootAsCMDGetShopHistory(ByteBuffer _bb, CMDGetShopHistory obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public CMDGetShopHistory __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public long uid() { int o = __offset(4); return o != 0 ? bb.getLong(o + bb_pos) : 0; }
  public boolean mutateUid(long uid) { int o = __offset(4); if (o != 0) { bb.putLong(o + bb_pos, uid); return true; } else { return false; } }
  public ShopHistoryItem history(int j) { return history(new ShopHistoryItem(), j); }
  public ShopHistoryItem history(ShopHistoryItem obj, int j) { int o = __offset(6); return o != 0 ? obj.__init(__indirect(__vector(o) + j * 4), bb) : null; }
  public int historyLength() { int o = __offset(6); return o != 0 ? __vector_len(o) : 0; }

  public static int createCMDGetShopHistory(FlatBufferBuilder builder,
      long uid,
      int historyOffset) {
    builder.startObject(2);
    CMDGetShopHistory.addUid(builder, uid);
    CMDGetShopHistory.addHistory(builder, historyOffset);
    return CMDGetShopHistory.endCMDGetShopHistory(builder);
  }

  public static void startCMDGetShopHistory(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addUid(FlatBufferBuilder builder, long uid) { builder.addLong(0, uid, 0); }
  public static void addHistory(FlatBufferBuilder builder, int historyOffset) { builder.addOffset(1, historyOffset, 0); }
  public static int createHistoryVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startHistoryVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endCMDGetShopHistory(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

