// automatically generated by the FlatBuffers compiler, do not modify

package vn.com.vng.gsmobile.casino.flatbuffers;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class CMDGetGameInfo extends Table {
  public static CMDGetGameInfo getRootAsCMDGetGameInfo(ByteBuffer _bb) { return getRootAsCMDGetGameInfo(_bb, new CMDGetGameInfo()); }
  public static CMDGetGameInfo getRootAsCMDGetGameInfo(ByteBuffer _bb, CMDGetGameInfo obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public CMDGetGameInfo __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public long roomId() { int o = __offset(4); return o != 0 ? bb.getLong(o + bb_pos) : 0; }
  public boolean mutateRoomId(long room_id) { int o = __offset(4); if (o != 0) { bb.putLong(o + bb_pos, room_id); return true; } else { return false; } }
  public long gameId() { int o = __offset(6); return o != 0 ? bb.getLong(o + bb_pos) : 0; }
  public boolean mutateGameId(long game_id) { int o = __offset(6); if (o != 0) { bb.putLong(o + bb_pos, game_id); return true; } else { return false; } }
  public long userId() { int o = __offset(8); return o != 0 ? bb.getLong(o + bb_pos) : 0; }
  public boolean mutateUserId(long user_id) { int o = __offset(8); if (o != 0) { bb.putLong(o + bb_pos, user_id); return true; } else { return false; } }

  public static int createCMDGetGameInfo(FlatBufferBuilder builder,
      long room_id,
      long game_id,
      long user_id) {
    builder.startObject(3);
    CMDGetGameInfo.addUserId(builder, user_id);
    CMDGetGameInfo.addGameId(builder, game_id);
    CMDGetGameInfo.addRoomId(builder, room_id);
    return CMDGetGameInfo.endCMDGetGameInfo(builder);
  }

  public static void startCMDGetGameInfo(FlatBufferBuilder builder) { builder.startObject(3); }
  public static void addRoomId(FlatBufferBuilder builder, long roomId) { builder.addLong(0, roomId, 0); }
  public static void addGameId(FlatBufferBuilder builder, long gameId) { builder.addLong(1, gameId, 0); }
  public static void addUserId(FlatBufferBuilder builder, long userId) { builder.addLong(2, userId, 0); }
  public static int endCMDGetGameInfo(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

