// automatically generated by the FlatBuffers compiler, do not modify

package vn.com.vng.gsmobile.casino.flatbuffers;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class CMDGameTLMNSkip extends Table {
  public static CMDGameTLMNSkip getRootAsCMDGameTLMNSkip(ByteBuffer _bb) { return getRootAsCMDGameTLMNSkip(_bb, new CMDGameTLMNSkip()); }
  public static CMDGameTLMNSkip getRootAsCMDGameTLMNSkip(ByteBuffer _bb, CMDGameTLMNSkip obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public CMDGameTLMNSkip __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public long roomId() { int o = __offset(4); return o != 0 ? bb.getLong(o + bb_pos) : 0; }
  public boolean mutateRoomId(long room_id) { int o = __offset(4); if (o != 0) { bb.putLong(o + bb_pos, room_id); return true; } else { return false; } }
  public long gameId() { int o = __offset(6); return o != 0 ? bb.getLong(o + bb_pos) : 0; }
  public boolean mutateGameId(long game_id) { int o = __offset(6); if (o != 0) { bb.putLong(o + bb_pos, game_id); return true; } else { return false; } }
  public int turnIdx() { int o = __offset(8); return o != 0 ? bb.get(o + bb_pos) & 0xFF : 0; }
  public boolean mutateTurnIdx(int turn_idx) { int o = __offset(8); if (o != 0) { bb.put(o + bb_pos, (byte)turn_idx); return true; } else { return false; } }
  public int playerIdx() { int o = __offset(10); return o != 0 ? bb.get(o + bb_pos) & 0xFF : 0; }
  public boolean mutatePlayerIdx(int player_idx) { int o = __offset(10); if (o != 0) { bb.put(o + bb_pos, (byte)player_idx); return true; } else { return false; } }

  public static int createCMDGameTLMNSkip(FlatBufferBuilder builder,
      long room_id,
      long game_id,
      int turn_idx,
      int player_idx) {
    builder.startObject(4);
    CMDGameTLMNSkip.addGameId(builder, game_id);
    CMDGameTLMNSkip.addRoomId(builder, room_id);
    CMDGameTLMNSkip.addPlayerIdx(builder, player_idx);
    CMDGameTLMNSkip.addTurnIdx(builder, turn_idx);
    return CMDGameTLMNSkip.endCMDGameTLMNSkip(builder);
  }

  public static void startCMDGameTLMNSkip(FlatBufferBuilder builder) { builder.startObject(4); }
  public static void addRoomId(FlatBufferBuilder builder, long roomId) { builder.addLong(0, roomId, 0); }
  public static void addGameId(FlatBufferBuilder builder, long gameId) { builder.addLong(1, gameId, 0); }
  public static void addTurnIdx(FlatBufferBuilder builder, int turnIdx) { builder.addByte(2, (byte)turnIdx, 0); }
  public static void addPlayerIdx(FlatBufferBuilder builder, int playerIdx) { builder.addByte(3, (byte)playerIdx, 0); }
  public static int endCMDGameTLMNSkip(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

