// automatically generated by the FlatBuffers compiler, do not modify

package vn.com.vng.gsmobile.casino.flatbuffers;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class CMDInviteGame extends Table {
  public static CMDInviteGame getRootAsCMDInviteGame(ByteBuffer _bb) { return getRootAsCMDInviteGame(_bb, new CMDInviteGame()); }
  public static CMDInviteGame getRootAsCMDInviteGame(ByteBuffer _bb, CMDInviteGame obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public CMDInviteGame __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public vn.com.vng.gsmobile.casino.flatbuffers.UserInfo from() { return from(new vn.com.vng.gsmobile.casino.flatbuffers.UserInfo()); }
  public vn.com.vng.gsmobile.casino.flatbuffers.UserInfo from(vn.com.vng.gsmobile.casino.flatbuffers.UserInfo obj) { int o = __offset(4); return o != 0 ? obj.__init(__indirect(o + bb_pos), bb) : null; }
  public long to(int j) { int o = __offset(6); return o != 0 ? bb.getLong(__vector(o) + j * 8) : 0; }
  public int toLength() { int o = __offset(6); return o != 0 ? __vector_len(o) : 0; }
  public ByteBuffer toAsByteBuffer() { return __vector_as_bytebuffer(6, 8); }
  public boolean mutateTo(int j, long to) { int o = __offset(6); if (o != 0) { bb.putLong(__vector(o) + j * 8, to); return true; } else { return false; } }
  public long roomId() { int o = __offset(8); return o != 0 ? bb.getLong(o + bb_pos) : 0; }
  public boolean mutateRoomId(long room_id) { int o = __offset(8); if (o != 0) { bb.putLong(o + bb_pos, room_id); return true; } else { return false; } }
  public int gameType() { int o = __offset(10); return o != 0 ? bb.get(o + bb_pos) & 0xFF : 0; }
  public boolean mutateGameType(int game_type) { int o = __offset(10); if (o != 0) { bb.put(o + bb_pos, (byte)game_type); return true; } else { return false; } }
  public long betValue() { int o = __offset(12); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0; }
  public boolean mutateBetValue(long bet_value) { int o = __offset(12); if (o != 0) { bb.putInt(o + bb_pos, (int)bet_value); return true; } else { return false; } }
  public String description() { int o = __offset(14); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer descriptionAsByteBuffer() { return __vector_as_bytebuffer(14, 1); }
  public String reqToken() { int o = __offset(16); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer reqTokenAsByteBuffer() { return __vector_as_bytebuffer(16, 1); }
  public String name() { int o = __offset(18); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer nameAsByteBuffer() { return __vector_as_bytebuffer(18, 1); }

  public static int createCMDInviteGame(FlatBufferBuilder builder,
      int fromOffset,
      int toOffset,
      long room_id,
      int game_type,
      long bet_value,
      int descriptionOffset,
      int req_tokenOffset,
      int nameOffset) {
    builder.startObject(8);
    CMDInviteGame.addRoomId(builder, room_id);
    CMDInviteGame.addName(builder, nameOffset);
    CMDInviteGame.addReqToken(builder, req_tokenOffset);
    CMDInviteGame.addDescription(builder, descriptionOffset);
    CMDInviteGame.addBetValue(builder, bet_value);
    CMDInviteGame.addTo(builder, toOffset);
    CMDInviteGame.addFrom(builder, fromOffset);
    CMDInviteGame.addGameType(builder, game_type);
    return CMDInviteGame.endCMDInviteGame(builder);
  }

  public static void startCMDInviteGame(FlatBufferBuilder builder) { builder.startObject(8); }
  public static void addFrom(FlatBufferBuilder builder, int fromOffset) { builder.addOffset(0, fromOffset, 0); }
  public static void addTo(FlatBufferBuilder builder, int toOffset) { builder.addOffset(1, toOffset, 0); }
  public static int createToVector(FlatBufferBuilder builder, long[] data) { builder.startVector(8, data.length, 8); for (int i = data.length - 1; i >= 0; i--) builder.addLong(data[i]); return builder.endVector(); }
  public static void startToVector(FlatBufferBuilder builder, int numElems) { builder.startVector(8, numElems, 8); }
  public static void addRoomId(FlatBufferBuilder builder, long roomId) { builder.addLong(2, roomId, 0); }
  public static void addGameType(FlatBufferBuilder builder, int gameType) { builder.addByte(3, (byte)gameType, 0); }
  public static void addBetValue(FlatBufferBuilder builder, long betValue) { builder.addInt(4, (int)betValue, 0); }
  public static void addDescription(FlatBufferBuilder builder, int descriptionOffset) { builder.addOffset(5, descriptionOffset, 0); }
  public static void addReqToken(FlatBufferBuilder builder, int reqTokenOffset) { builder.addOffset(6, reqTokenOffset, 0); }
  public static void addName(FlatBufferBuilder builder, int nameOffset) { builder.addOffset(7, nameOffset, 0); }
  public static int endCMDInviteGame(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

