// automatically generated by the FlatBuffers compiler, do not modify

package vn.com.vng.gsmobile.casino.flatbuffers;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class CMDInviteFriend extends Table {
  public static CMDInviteFriend getRootAsCMDInviteFriend(ByteBuffer _bb) { return getRootAsCMDInviteFriend(_bb, new CMDInviteFriend()); }
  public static CMDInviteFriend getRootAsCMDInviteFriend(ByteBuffer _bb, CMDInviteFriend obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public CMDInviteFriend __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public long uid() { int o = __offset(4); return o != 0 ? bb.getLong(o + bb_pos) : 0; }
  public boolean mutateUid(long uid) { int o = __offset(4); if (o != 0) { bb.putLong(o + bb_pos, uid); return true; } else { return false; } }
  public String inviteList(int j) { int o = __offset(6); return o != 0 ? __string(__vector(o) + j * 4) : null; }
  public int inviteListLength() { int o = __offset(6); return o != 0 ? __vector_len(o) : 0; }
  public long inviteDoneCount() { int o = __offset(8); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0; }
  public boolean mutateInviteDoneCount(long invite_done_count) { int o = __offset(8); if (o != 0) { bb.putInt(o + bb_pos, (int)invite_done_count); return true; } else { return false; } }

  public static int createCMDInviteFriend(FlatBufferBuilder builder,
      long uid,
      int invite_listOffset,
      long invite_done_count) {
    builder.startObject(3);
    CMDInviteFriend.addUid(builder, uid);
    CMDInviteFriend.addInviteDoneCount(builder, invite_done_count);
    CMDInviteFriend.addInviteList(builder, invite_listOffset);
    return CMDInviteFriend.endCMDInviteFriend(builder);
  }

  public static void startCMDInviteFriend(FlatBufferBuilder builder) { builder.startObject(3); }
  public static void addUid(FlatBufferBuilder builder, long uid) { builder.addLong(0, uid, 0); }
  public static void addInviteList(FlatBufferBuilder builder, int inviteListOffset) { builder.addOffset(1, inviteListOffset, 0); }
  public static int createInviteListVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startInviteListVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addInviteDoneCount(FlatBufferBuilder builder, long inviteDoneCount) { builder.addInt(2, (int)inviteDoneCount, 0); }
  public static int endCMDInviteFriend(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

