// automatically generated by the FlatBuffers compiler, do not modify

package vn.com.vng.gsmobile.casino.flatbuffers;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class CMDReceivedAchievementReward extends Table {
  public static CMDReceivedAchievementReward getRootAsCMDReceivedAchievementReward(ByteBuffer _bb) { return getRootAsCMDReceivedAchievementReward(_bb, new CMDReceivedAchievementReward()); }
  public static CMDReceivedAchievementReward getRootAsCMDReceivedAchievementReward(ByteBuffer _bb, CMDReceivedAchievementReward obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public CMDReceivedAchievementReward __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public long uid() { int o = __offset(4); return o != 0 ? bb.getLong(o + bb_pos) : 0; }
  public boolean mutateUid(long uid) { int o = __offset(4); if (o != 0) { bb.putLong(o + bb_pos, uid); return true; } else { return false; } }
  public long id() { int o = __offset(6); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0; }
  public boolean mutateId(long id) { int o = __offset(6); if (o != 0) { bb.putInt(o + bb_pos, (int)id); return true; } else { return false; } }
  public long level() { int o = __offset(8); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0; }
  public boolean mutateLevel(long level) { int o = __offset(8); if (o != 0) { bb.putInt(o + bb_pos, (int)level); return true; } else { return false; } }
  public int type() { int o = __offset(10); return o != 0 ? bb.get(o + bb_pos) & 0xFF : 0; }
  public boolean mutateType(int type) { int o = __offset(10); if (o != 0) { bb.put(o + bb_pos, (byte)type); return true; } else { return false; } }
  public vn.com.vng.gsmobile.casino.flatbuffers.GiftItem reward() { return reward(new vn.com.vng.gsmobile.casino.flatbuffers.GiftItem()); }
  public vn.com.vng.gsmobile.casino.flatbuffers.GiftItem reward(vn.com.vng.gsmobile.casino.flatbuffers.GiftItem obj) { int o = __offset(12); return o != 0 ? obj.__init(__indirect(o + bb_pos), bb) : null; }
  public String reqToken() { int o = __offset(14); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer reqTokenAsByteBuffer() { return __vector_as_bytebuffer(14, 1); }

  public static int createCMDReceivedAchievementReward(FlatBufferBuilder builder,
      long uid,
      long id,
      long level,
      int type,
      int rewardOffset,
      int req_tokenOffset) {
    builder.startObject(6);
    CMDReceivedAchievementReward.addUid(builder, uid);
    CMDReceivedAchievementReward.addReqToken(builder, req_tokenOffset);
    CMDReceivedAchievementReward.addReward(builder, rewardOffset);
    CMDReceivedAchievementReward.addLevel(builder, level);
    CMDReceivedAchievementReward.addId(builder, id);
    CMDReceivedAchievementReward.addType(builder, type);
    return CMDReceivedAchievementReward.endCMDReceivedAchievementReward(builder);
  }

  public static void startCMDReceivedAchievementReward(FlatBufferBuilder builder) { builder.startObject(6); }
  public static void addUid(FlatBufferBuilder builder, long uid) { builder.addLong(0, uid, 0); }
  public static void addId(FlatBufferBuilder builder, long id) { builder.addInt(1, (int)id, 0); }
  public static void addLevel(FlatBufferBuilder builder, long level) { builder.addInt(2, (int)level, 0); }
  public static void addType(FlatBufferBuilder builder, int type) { builder.addByte(3, (byte)type, 0); }
  public static void addReward(FlatBufferBuilder builder, int rewardOffset) { builder.addOffset(4, rewardOffset, 0); }
  public static void addReqToken(FlatBufferBuilder builder, int reqTokenOffset) { builder.addOffset(5, reqTokenOffset, 0); }
  public static int endCMDReceivedAchievementReward(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

