// automatically generated by the FlatBuffers compiler, do not modify

package vn.com.vng.gsmobile.casino.flatbuffers;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class CMDRankList extends Table {
  public static CMDRankList getRootAsCMDRankList(ByteBuffer _bb) { return getRootAsCMDRankList(_bb, new CMDRankList()); }
  public static CMDRankList getRootAsCMDRankList(ByteBuffer _bb, CMDRankList obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public CMDRankList __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public long uid() { int o = __offset(4); return o != 0 ? bb.getLong(o + bb_pos) : 0; }
  public boolean mutateUid(long uid) { int o = __offset(4); if (o != 0) { bb.putLong(o + bb_pos, uid); return true; } else { return false; } }
  public int myRank() { int o = __offset(6); return o != 0 ? bb.getShort(o + bb_pos) & 0xFFFF : 0; }
  public boolean mutateMyRank(int my_rank) { int o = __offset(6); if (o != 0) { bb.putShort(o + bb_pos, (short)my_rank); return true; } else { return false; } }
  public long myScore() { int o = __offset(8); return o != 0 ? bb.getLong(o + bb_pos) : 0; }
  public boolean mutateMyScore(long my_score) { int o = __offset(8); if (o != 0) { bb.putLong(o + bb_pos, my_score); return true; } else { return false; } }
  public int type() { int o = __offset(10); return o != 0 ? bb.get(o + bb_pos) & 0xFF : 0; }
  public boolean mutateType(int type) { int o = __offset(10); if (o != 0) { bb.put(o + bb_pos, (byte)type); return true; } else { return false; } }
  public int offset() { int o = __offset(12); return o != 0 ? bb.getShort(o + bb_pos) & 0xFFFF : 0; }
  public boolean mutateOffset(int offset) { int o = __offset(12); if (o != 0) { bb.putShort(o + bb_pos, (short)offset); return true; } else { return false; } }
  public RankUser list(int j) { return list(new RankUser(), j); }
  public RankUser list(RankUser obj, int j) { int o = __offset(14); return o != 0 ? obj.__init(__indirect(__vector(o) + j * 4), bb) : null; }
  public int listLength() { int o = __offset(14); return o != 0 ? __vector_len(o) : 0; }

  public static int createCMDRankList(FlatBufferBuilder builder,
      long uid,
      int my_rank,
      long my_score,
      int type,
      int offset,
      int listOffset) {
    builder.startObject(6);
    CMDRankList.addMyScore(builder, my_score);
    CMDRankList.addUid(builder, uid);
    CMDRankList.addList(builder, listOffset);
    CMDRankList.addOffset(builder, offset);
    CMDRankList.addMyRank(builder, my_rank);
    CMDRankList.addType(builder, type);
    return CMDRankList.endCMDRankList(builder);
  }

  public static void startCMDRankList(FlatBufferBuilder builder) { builder.startObject(6); }
  public static void addUid(FlatBufferBuilder builder, long uid) { builder.addLong(0, uid, 0); }
  public static void addMyRank(FlatBufferBuilder builder, int myRank) { builder.addShort(1, (short)myRank, 0); }
  public static void addMyScore(FlatBufferBuilder builder, long myScore) { builder.addLong(2, myScore, 0); }
  public static void addType(FlatBufferBuilder builder, int type) { builder.addByte(3, (byte)type, 0); }
  public static void addOffset(FlatBufferBuilder builder, int offset) { builder.addShort(4, (short)offset, 0); }
  public static void addList(FlatBufferBuilder builder, int listOffset) { builder.addOffset(5, listOffset, 0); }
  public static int createListVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startListVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endCMDRankList(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

