// automatically generated by the FlatBuffers compiler, do not modify

package vn.com.vng.gsmobile.casino.flatbuffers;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class CMDReceiveGiftCode extends Table {
  public static CMDReceiveGiftCode getRootAsCMDReceiveGiftCode(ByteBuffer _bb) { return getRootAsCMDReceiveGiftCode(_bb, new CMDReceiveGiftCode()); }
  public static CMDReceiveGiftCode getRootAsCMDReceiveGiftCode(ByteBuffer _bb, CMDReceiveGiftCode obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public CMDReceiveGiftCode __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public long uid() { int o = __offset(4); return o != 0 ? bb.getLong(o + bb_pos) : 0; }
  public boolean mutateUid(long uid) { int o = __offset(4); if (o != 0) { bb.putLong(o + bb_pos, uid); return true; } else { return false; } }
  public String giftCode() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer giftCodeAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public GiftItem gift() { return gift(new GiftItem()); }
  public GiftItem gift(GiftItem obj) { int o = __offset(8); return o != 0 ? obj.__init(__indirect(o + bb_pos), bb) : null; }

  public static int createCMDReceiveGiftCode(FlatBufferBuilder builder,
      long uid,
      int gift_codeOffset,
      int giftOffset) {
    builder.startObject(3);
    CMDReceiveGiftCode.addUid(builder, uid);
    CMDReceiveGiftCode.addGift(builder, giftOffset);
    CMDReceiveGiftCode.addGiftCode(builder, gift_codeOffset);
    return CMDReceiveGiftCode.endCMDReceiveGiftCode(builder);
  }

  public static void startCMDReceiveGiftCode(FlatBufferBuilder builder) { builder.startObject(3); }
  public static void addUid(FlatBufferBuilder builder, long uid) { builder.addLong(0, uid, 0); }
  public static void addGiftCode(FlatBufferBuilder builder, int giftCodeOffset) { builder.addOffset(1, giftCodeOffset, 0); }
  public static void addGift(FlatBufferBuilder builder, int giftOffset) { builder.addOffset(2, giftOffset, 0); }
  public static int endCMDReceiveGiftCode(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

