// automatically generated by the FlatBuffers compiler, do not modify

package vn.com.vng.gsmobile.casino.flatbuffers;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class CMDShareGame extends Table {
  public static CMDShareGame getRootAsCMDShareGame(ByteBuffer _bb) { return getRootAsCMDShareGame(_bb, new CMDShareGame()); }
  public static CMDShareGame getRootAsCMDShareGame(ByteBuffer _bb, CMDShareGame obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public CMDShareGame __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public long uid() { int o = __offset(4); return o != 0 ? bb.getLong(o + bb_pos) : 0; }
  public boolean mutateUid(long uid) { int o = __offset(4); if (o != 0) { bb.putLong(o + bb_pos, uid); return true; } else { return false; } }

  public static int createCMDShareGame(FlatBufferBuilder builder,
      long uid) {
    builder.startObject(1);
    CMDShareGame.addUid(builder, uid);
    return CMDShareGame.endCMDShareGame(builder);
  }

  public static void startCMDShareGame(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addUid(FlatBufferBuilder builder, long uid) { builder.addLong(0, uid, 0); }
  public static int endCMDShareGame(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

