// automatically generated by the FlatBuffers compiler, do not modify

package vn.com.vng.gsmobile.casino.flatbuffers;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class CMDSendMail extends Table {
  public static CMDSendMail getRootAsCMDSendMail(ByteBuffer _bb) { return getRootAsCMDSendMail(_bb, new CMDSendMail()); }
  public static CMDSendMail getRootAsCMDSendMail(ByteBuffer _bb, CMDSendMail obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public CMDSendMail __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public long from() { int o = __offset(4); return o != 0 ? bb.getLong(o + bb_pos) : 0; }
  public boolean mutateFrom(long from) { int o = __offset(4); if (o != 0) { bb.putLong(o + bb_pos, from); return true; } else { return false; } }
  public long toUid() { int o = __offset(6); return o != 0 ? bb.getLong(o + bb_pos) : 0; }
  public boolean mutateToUid(long to_uid) { int o = __offset(6); if (o != 0) { bb.putLong(o + bb_pos, to_uid); return true; } else { return false; } }
  public String message() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer messageAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }

  public static int createCMDSendMail(FlatBufferBuilder builder,
      long from,
      long to_uid,
      int messageOffset) {
    builder.startObject(3);
    CMDSendMail.addToUid(builder, to_uid);
    CMDSendMail.addFrom(builder, from);
    CMDSendMail.addMessage(builder, messageOffset);
    return CMDSendMail.endCMDSendMail(builder);
  }

  public static void startCMDSendMail(FlatBufferBuilder builder) { builder.startObject(3); }
  public static void addFrom(FlatBufferBuilder builder, long from) { builder.addLong(0, from, 0); }
  public static void addToUid(FlatBufferBuilder builder, long toUid) { builder.addLong(1, toUid, 0); }
  public static void addMessage(FlatBufferBuilder builder, int messageOffset) { builder.addOffset(2, messageOffset, 0); }
  public static int endCMDSendMail(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

