// automatically generated by the FlatBuffers compiler, do not modify

package vn.com.vng.gsmobile.casino.flatbuffers;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class EventList extends Table {
  public static EventList getRootAsEventList(ByteBuffer _bb) { return getRootAsEventList(_bb, new EventList()); }
  public static EventList getRootAsEventList(ByteBuffer _bb, EventList obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public EventList __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public long uid() { int o = __offset(4); return o != 0 ? bb.getLong(o + bb_pos) : 0; }
  public boolean mutateUid(long uid) { int o = __offset(4); if (o != 0) { bb.putLong(o + bb_pos, uid); return true; } else { return false; } }
  public EventInfo events(int j) { return events(new EventInfo(), j); }
  public EventInfo events(EventInfo obj, int j) { int o = __offset(6); return o != 0 ? obj.__init(__indirect(__vector(o) + j * 4), bb) : null; }
  public int eventsLength() { int o = __offset(6); return o != 0 ? __vector_len(o) : 0; }

  public static int createEventList(FlatBufferBuilder builder,
      long uid,
      int eventsOffset) {
    builder.startObject(2);
    EventList.addUid(builder, uid);
    EventList.addEvents(builder, eventsOffset);
    return EventList.endEventList(builder);
  }

  public static void startEventList(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addUid(FlatBufferBuilder builder, long uid) { builder.addLong(0, uid, 0); }
  public static void addEvents(FlatBufferBuilder builder, int eventsOffset) { builder.addOffset(1, eventsOffset, 0); }
  public static int createEventsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startEventsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endEventList(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

