// automatically generated by the FlatBuffers compiler, do not modify

package vn.com.vng.gsmobile.casino.flatbuffers;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class EventInfo extends Table {
  public static EventInfo getRootAsEventInfo(ByteBuffer _bb) { return getRootAsEventInfo(_bb, new EventInfo()); }
  public static EventInfo getRootAsEventInfo(ByteBuffer _bb, EventInfo obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public EventInfo __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public long id() { int o = __offset(4); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0; }
  public boolean mutateId(long id) { int o = __offset(4); if (o != 0) { bb.putInt(o + bb_pos, (int)id); return true; } else { return false; } }
  public int type() { int o = __offset(6); return o != 0 ? bb.get(o + bb_pos) & 0xFF : 0; }
  public boolean mutateType(int type) { int o = __offset(6); if (o != 0) { bb.put(o + bb_pos, (byte)type); return true; } else { return false; } }
  public String name() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer nameAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public long startTime() { int o = __offset(10); return o != 0 ? bb.getLong(o + bb_pos) : 0; }
  public boolean mutateStartTime(long start_time) { int o = __offset(10); if (o != 0) { bb.putLong(o + bb_pos, start_time); return true; } else { return false; } }
  public long endTime() { int o = __offset(12); return o != 0 ? bb.getLong(o + bb_pos) : 0; }
  public boolean mutateEndTime(long end_time) { int o = __offset(12); if (o != 0) { bb.putLong(o + bb_pos, end_time); return true; } else { return false; } }
  public long bannerStartTime() { int o = __offset(14); return o != 0 ? bb.getLong(o + bb_pos) : 0; }
  public boolean mutateBannerStartTime(long banner_start_time) { int o = __offset(14); if (o != 0) { bb.putLong(o + bb_pos, banner_start_time); return true; } else { return false; } }
  public long bannerEndTime() { int o = __offset(16); return o != 0 ? bb.getLong(o + bb_pos) : 0; }
  public boolean mutateBannerEndTime(long banner_end_time) { int o = __offset(16); if (o != 0) { bb.putLong(o + bb_pos, banner_end_time); return true; } else { return false; } }
  public long promo() { int o = __offset(18); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0; }
  public boolean mutatePromo(long promo) { int o = __offset(18); if (o != 0) { bb.putInt(o + bb_pos, (int)promo); return true; } else { return false; } }
  public int discount() { int o = __offset(20); return o != 0 ? bb.get(o + bb_pos) & 0xFF : 0; }
  public boolean mutateDiscount(int discount) { int o = __offset(20); if (o != 0) { bb.put(o + bb_pos, (byte)discount); return true; } else { return false; } }
  public String description() { int o = __offset(22); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer descriptionAsByteBuffer() { return __vector_as_bytebuffer(22, 1); }
  public String fanpageUrl() { int o = __offset(24); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer fanpageUrlAsByteBuffer() { return __vector_as_bytebuffer(24, 1); }
  public String bannerUrl() { int o = __offset(26); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer bannerUrlAsByteBuffer() { return __vector_as_bytebuffer(26, 1); }
  public String bannerTinyUrl() { int o = __offset(28); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer bannerTinyUrlAsByteBuffer() { return __vector_as_bytebuffer(28, 1); }
  public int rank(int j) { int o = __offset(30); return o != 0 ? bb.get(__vector(o) + j * 1) & 0xFF : 0; }
  public int rankLength() { int o = __offset(30); return o != 0 ? __vector_len(o) : 0; }
  public ByteBuffer rankAsByteBuffer() { return __vector_as_bytebuffer(30, 1); }
  public boolean mutateRank(int j, int rank) { int o = __offset(30); if (o != 0) { bb.put(__vector(o) + j * 1, (byte)rank); return true; } else { return false; } }

  public static int createEventInfo(FlatBufferBuilder builder,
      long id,
      int type,
      int nameOffset,
      long start_time,
      long end_time,
      long banner_start_time,
      long banner_end_time,
      long promo,
      int discount,
      int descriptionOffset,
      int fanpage_urlOffset,
      int banner_urlOffset,
      int banner_tiny_urlOffset,
      int rankOffset) {
    builder.startObject(14);
    EventInfo.addBannerEndTime(builder, banner_end_time);
    EventInfo.addBannerStartTime(builder, banner_start_time);
    EventInfo.addEndTime(builder, end_time);
    EventInfo.addStartTime(builder, start_time);
    EventInfo.addRank(builder, rankOffset);
    EventInfo.addBannerTinyUrl(builder, banner_tiny_urlOffset);
    EventInfo.addBannerUrl(builder, banner_urlOffset);
    EventInfo.addFanpageUrl(builder, fanpage_urlOffset);
    EventInfo.addDescription(builder, descriptionOffset);
    EventInfo.addPromo(builder, promo);
    EventInfo.addName(builder, nameOffset);
    EventInfo.addId(builder, id);
    EventInfo.addDiscount(builder, discount);
    EventInfo.addType(builder, type);
    return EventInfo.endEventInfo(builder);
  }

  public static void startEventInfo(FlatBufferBuilder builder) { builder.startObject(14); }
  public static void addId(FlatBufferBuilder builder, long id) { builder.addInt(0, (int)id, 0); }
  public static void addType(FlatBufferBuilder builder, int type) { builder.addByte(1, (byte)type, 0); }
  public static void addName(FlatBufferBuilder builder, int nameOffset) { builder.addOffset(2, nameOffset, 0); }
  public static void addStartTime(FlatBufferBuilder builder, long startTime) { builder.addLong(3, startTime, 0); }
  public static void addEndTime(FlatBufferBuilder builder, long endTime) { builder.addLong(4, endTime, 0); }
  public static void addBannerStartTime(FlatBufferBuilder builder, long bannerStartTime) { builder.addLong(5, bannerStartTime, 0); }
  public static void addBannerEndTime(FlatBufferBuilder builder, long bannerEndTime) { builder.addLong(6, bannerEndTime, 0); }
  public static void addPromo(FlatBufferBuilder builder, long promo) { builder.addInt(7, (int)promo, 0); }
  public static void addDiscount(FlatBufferBuilder builder, int discount) { builder.addByte(8, (byte)discount, 0); }
  public static void addDescription(FlatBufferBuilder builder, int descriptionOffset) { builder.addOffset(9, descriptionOffset, 0); }
  public static void addFanpageUrl(FlatBufferBuilder builder, int fanpageUrlOffset) { builder.addOffset(10, fanpageUrlOffset, 0); }
  public static void addBannerUrl(FlatBufferBuilder builder, int bannerUrlOffset) { builder.addOffset(11, bannerUrlOffset, 0); }
  public static void addBannerTinyUrl(FlatBufferBuilder builder, int bannerTinyUrlOffset) { builder.addOffset(12, bannerTinyUrlOffset, 0); }
  public static void addRank(FlatBufferBuilder builder, int rankOffset) { builder.addOffset(13, rankOffset, 0); }
  public static int createRankVector(FlatBufferBuilder builder, byte[] data) { builder.startVector(1, data.length, 1); for (int i = data.length - 1; i >= 0; i--) builder.addByte(data[i]); return builder.endVector(); }
  public static void startRankVector(FlatBufferBuilder builder, int numElems) { builder.startVector(1, numElems, 1); }
  public static int endEventInfo(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

