// automatically generated by the FlatBuffers compiler, do not modify

package vn.com.vng.gsmobile.casino.flatbuffers;

public final class EventType {
  private EventType() { }
  public static final byte Event_None = 0;
  public static final byte Event_Normal = 1;
  public static final byte Event_Rank = 2;
  public static final byte Event_Buy = 3;
  public static final byte Event_Buy_VIP = 4;
  public static final byte Event_Buy_Item = 5;
  public static final byte Event_Spin = 6;

  public static final String[] names = { "Event_None", "Event_Normal", "Event_Rank", "Event_Buy", "Event_Buy_VIP", "Event_Buy_Item", "Event_Spin", };

  public static String name(int e) { return names[e]; }
}

