// automatically generated by the FlatBuffers compiler, do not modify

package vn.com.vng.gsmobile.casino.flatbuffers;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class GameMBShowCardUpdate extends Table {
  public static GameMBShowCardUpdate getRootAsGameMBShowCardUpdate(ByteBuffer _bb) { return getRootAsGameMBShowCardUpdate(_bb, new GameMBShowCardUpdate()); }
  public static GameMBShowCardUpdate getRootAsGameMBShowCardUpdate(ByteBuffer _bb, GameMBShowCardUpdate obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public GameMBShowCardUpdate __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public int playerIdx() { int o = __offset(4); return o != 0 ? bb.get(o + bb_pos) & 0xFF : 0; }
  public boolean mutatePlayerIdx(int player_idx) { int o = __offset(4); if (o != 0) { bb.put(o + bb_pos, (byte)player_idx); return true; } else { return false; } }
  public int showType() { int o = __offset(6); return o != 0 ? bb.get(o + bb_pos) & 0xFF : 0; }
  public boolean mutateShowType(int show_type) { int o = __offset(6); if (o != 0) { bb.put(o + bb_pos, (byte)show_type); return true; } else { return false; } }

  public static int createGameMBShowCardUpdate(FlatBufferBuilder builder,
      int player_idx,
      int show_type) {
    builder.startObject(2);
    GameMBShowCardUpdate.addShowType(builder, show_type);
    GameMBShowCardUpdate.addPlayerIdx(builder, player_idx);
    return GameMBShowCardUpdate.endGameMBShowCardUpdate(builder);
  }

  public static void startGameMBShowCardUpdate(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addPlayerIdx(FlatBufferBuilder builder, int playerIdx) { builder.addByte(0, (byte)playerIdx, 0); }
  public static void addShowType(FlatBufferBuilder builder, int showType) { builder.addByte(1, (byte)showType, 0); }
  public static int endGameMBShowCardUpdate(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

