// automatically generated by the FlatBuffers compiler, do not modify

package vn.com.vng.gsmobile.casino.flatbuffers;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class GameMBResultDetail extends Table {
  public static GameMBResultDetail getRootAsGameMBResultDetail(ByteBuffer _bb) { return getRootAsGameMBResultDetail(_bb, new GameMBResultDetail()); }
  public static GameMBResultDetail getRootAsGameMBResultDetail(ByteBuffer _bb, GameMBResultDetail obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public GameMBResultDetail __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public long goldBinhLung() { int o = __offset(4); return o != 0 ? bb.getLong(o + bb_pos) : 0; }
  public boolean mutateGoldBinhLung(long gold_binh_lung) { int o = __offset(4); if (o != 0) { bb.putLong(o + bb_pos, gold_binh_lung); return true; } else { return false; } }
  public long goldMauBinh() { int o = __offset(6); return o != 0 ? bb.getLong(o + bb_pos) : 0; }
  public boolean mutateGoldMauBinh(long gold_mau_binh) { int o = __offset(6); if (o != 0) { bb.putLong(o + bb_pos, gold_mau_binh); return true; } else { return false; } }
  public long goldChi1() { int o = __offset(8); return o != 0 ? bb.getLong(o + bb_pos) : 0; }
  public boolean mutateGoldChi1(long gold_chi_1) { int o = __offset(8); if (o != 0) { bb.putLong(o + bb_pos, gold_chi_1); return true; } else { return false; } }
  public long goldChi2() { int o = __offset(10); return o != 0 ? bb.getLong(o + bb_pos) : 0; }
  public boolean mutateGoldChi2(long gold_chi_2) { int o = __offset(10); if (o != 0) { bb.putLong(o + bb_pos, gold_chi_2); return true; } else { return false; } }
  public long goldChi3() { int o = __offset(12); return o != 0 ? bb.getLong(o + bb_pos) : 0; }
  public boolean mutateGoldChi3(long gold_chi_3) { int o = __offset(12); if (o != 0) { bb.putLong(o + bb_pos, gold_chi_3); return true; } else { return false; } }
  public long goldSapHo() { int o = __offset(14); return o != 0 ? bb.getLong(o + bb_pos) : 0; }
  public boolean mutateGoldSapHo(long gold_sap_ho) { int o = __offset(14); if (o != 0) { bb.putLong(o + bb_pos, gold_sap_ho); return true; } else { return false; } }
  public long goldSapLang() { int o = __offset(16); return o != 0 ? bb.getLong(o + bb_pos) : 0; }
  public boolean mutateGoldSapLang(long gold_sap_lang) { int o = __offset(16); if (o != 0) { bb.putLong(o + bb_pos, gold_sap_lang); return true; } else { return false; } }
  public byte resultStatus() { int o = __offset(18); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public boolean mutateResultStatus(byte result_status) { int o = __offset(18); if (o != 0) { bb.put(o + bb_pos, result_status); return true; } else { return false; } }

  public static int createGameMBResultDetail(FlatBufferBuilder builder,
      long gold_binh_lung,
      long gold_mau_binh,
      long gold_chi_1,
      long gold_chi_2,
      long gold_chi_3,
      long gold_sap_ho,
      long gold_sap_lang,
      byte result_status) {
    builder.startObject(8);
    GameMBResultDetail.addGoldSapLang(builder, gold_sap_lang);
    GameMBResultDetail.addGoldSapHo(builder, gold_sap_ho);
    GameMBResultDetail.addGoldChi3(builder, gold_chi_3);
    GameMBResultDetail.addGoldChi2(builder, gold_chi_2);
    GameMBResultDetail.addGoldChi1(builder, gold_chi_1);
    GameMBResultDetail.addGoldMauBinh(builder, gold_mau_binh);
    GameMBResultDetail.addGoldBinhLung(builder, gold_binh_lung);
    GameMBResultDetail.addResultStatus(builder, result_status);
    return GameMBResultDetail.endGameMBResultDetail(builder);
  }

  public static void startGameMBResultDetail(FlatBufferBuilder builder) { builder.startObject(8); }
  public static void addGoldBinhLung(FlatBufferBuilder builder, long goldBinhLung) { builder.addLong(0, goldBinhLung, 0); }
  public static void addGoldMauBinh(FlatBufferBuilder builder, long goldMauBinh) { builder.addLong(1, goldMauBinh, 0); }
  public static void addGoldChi1(FlatBufferBuilder builder, long goldChi1) { builder.addLong(2, goldChi1, 0); }
  public static void addGoldChi2(FlatBufferBuilder builder, long goldChi2) { builder.addLong(3, goldChi2, 0); }
  public static void addGoldChi3(FlatBufferBuilder builder, long goldChi3) { builder.addLong(4, goldChi3, 0); }
  public static void addGoldSapHo(FlatBufferBuilder builder, long goldSapHo) { builder.addLong(5, goldSapHo, 0); }
  public static void addGoldSapLang(FlatBufferBuilder builder, long goldSapLang) { builder.addLong(6, goldSapLang, 0); }
  public static void addResultStatus(FlatBufferBuilder builder, byte resultStatus) { builder.addByte(7, resultStatus, 0); }
  public static int endGameMBResultDetail(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

