// automatically generated by the FlatBuffers compiler, do not modify

package vn.com.vng.gsmobile.casino.flatbuffers;

public final class GameType {
  private GameType() { }
  public static final byte None = 0;
  public static final byte TLMN = 1;
  public static final byte TALA = 2;
  public static final byte BALA = 3;
  public static final byte MAUBINH = 4;

  public static final String[] names = { "None", "TLMN", "TALA", "BALA", "MAUBINH", };

  public static String name(int e) { return names[e]; }
}

