// automatically generated by the FlatBuffers compiler, do not modify

package vn.com.vng.gsmobile.casino.flatbuffers;

public final class GameRoomState {
  private GameRoomState() { }
  public static final byte Destroyed = 0;
  public static final byte Idle = 1;
  public static final byte Waiting_Player = 2;
  public static final byte Waiting_Game = 3;
  public static final byte Playing = 4;
  public static final byte Finished = 5;

  public static final String[] names = { "Destroyed", "Idle", "Waiting_Player", "Waiting_Game", "Playing", "Finished", };

  public static String name(int e) { return names[e]; }
}

