// automatically generated by the FlatBuffers compiler, do not modify

package vn.com.vng.gsmobile.casino.flatbuffers;

public final class GiftSource {
  private GiftSource() { }
  public static final byte From_None = 0;
  public static final byte From_DailyGifts = 1;
  public static final byte From_VipGifts = 2;
  public static final byte From_SystemGifts = 3;
  public static final byte From_GiftCode = 4;

  public static final String[] names = { "From_None", "From_DailyGifts", "From_VipGifts", "From_SystemGifts", "From_GiftCode", };

  public static String name(int e) { return names[e]; }
}

