// automatically generated by the FlatBuffers compiler, do not modify

package vn.com.vng.gsmobile.casino.flatbuffers;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class Gift extends Table {
  public static Gift getRootAsGift(ByteBuffer _bb) { return getRootAsGift(_bb, new Gift()); }
  public static Gift getRootAsGift(ByteBuffer _bb, Gift obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public Gift __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public int type() { int o = __offset(4); return o != 0 ? bb.get(o + bb_pos) & 0xFF : 0; }
  public boolean mutateType(int type) { int o = __offset(4); if (o != 0) { bb.put(o + bb_pos, (byte)type); return true; } else { return false; } }
  public long value() { int o = __offset(6); return o != 0 ? bb.getLong(o + bb_pos) : 0; }
  public boolean mutateValue(long value) { int o = __offset(6); if (o != 0) { bb.putLong(o + bb_pos, value); return true; } else { return false; } }

  public static int createGift(FlatBufferBuilder builder,
      int type,
      long value) {
    builder.startObject(2);
    Gift.addValue(builder, value);
    Gift.addType(builder, type);
    return Gift.endGift(builder);
  }

  public static void startGift(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addType(FlatBufferBuilder builder, int type) { builder.addByte(0, (byte)type, 0); }
  public static void addValue(FlatBufferBuilder builder, long value) { builder.addLong(1, value, 0); }
  public static int endGift(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

