// automatically generated by the FlatBuffers compiler, do not modify

package vn.com.vng.gsmobile.casino.flatbuffers;

public final class ItemCostType {
  private ItemCostType() { }
  public static final byte Cost_Free = 0;
  public static final byte Cost_Coin = 1;
  public static final byte Cost_Star = 2;
  public static final byte Cost_Cash_Gateway = 11;
  public static final byte Cost_Cash_SMS = 12;
  public static final byte Cost_Cash_Card = 13;
  public static final byte Cost_Cash_IAP = 14;

  public static final String[] names = { "Cost_Free", "Cost_Coin", "Cost_Star", "", "", "", "", "", "", "", "", "Cost_Cash_Gateway", "Cost_Cash_SMS", "Cost_Cash_Card", "Cost_Cash_IAP", };

  public static String name(int e) { return names[e]; }
}

