// automatically generated by the FlatBuffers compiler, do not modify

package vn.com.vng.gsmobile.casino.flatbuffers;

public final class ItemType {
  private ItemType() { }
  public static final byte Item_None = 0;
  public static final byte Item_Coin = 1;
  public static final byte Item_Star = 2;
  public static final byte Item_VIP = 3;
  public static final byte Item_EXP = 4;

  public static final String[] names = { "Item_None", "Item_Coin", "Item_Star", "Item_VIP", "Item_EXP", };

  public static String name(int e) { return names[e]; }
}

