// automatically generated by the FlatBuffers compiler, do not modify

package vn.com.vng.gsmobile.casino.flatbuffers;

public final class JoinGameType {
  private JoinGameType() { }
  public static final byte PLAY = 0;
  public static final byte VIEW = 1;

  public static final String[] names = { "PLAY", "VIEW", };

  public static String name(int e) { return names[e]; }
}

