// automatically generated by the FlatBuffers compiler, do not modify

package vn.com.vng.gsmobile.casino.flatbuffers;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class ListUserStatus extends Table {
  public static ListUserStatus getRootAsListUserStatus(ByteBuffer _bb) { return getRootAsListUserStatus(_bb, new ListUserStatus()); }
  public static ListUserStatus getRootAsListUserStatus(ByteBuffer _bb, ListUserStatus obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public ListUserStatus __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public long uid(int j) { int o = __offset(4); return o != 0 ? bb.getLong(__vector(o) + j * 8) : 0; }
  public int uidLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }
  public ByteBuffer uidAsByteBuffer() { return __vector_as_bytebuffer(4, 8); }
  public boolean mutateUid(int j, long uid) { int o = __offset(4); if (o != 0) { bb.putLong(__vector(o) + j * 8, uid); return true; } else { return false; } }
  public UserStatusLoc status(int j) { return status(new UserStatusLoc(), j); }
  public UserStatusLoc status(UserStatusLoc obj, int j) { int o = __offset(6); return o != 0 ? obj.__init(__indirect(__vector(o) + j * 4), bb) : null; }
  public int statusLength() { int o = __offset(6); return o != 0 ? __vector_len(o) : 0; }

  public static int createListUserStatus(FlatBufferBuilder builder,
      int uidOffset,
      int statusOffset) {
    builder.startObject(2);
    ListUserStatus.addStatus(builder, statusOffset);
    ListUserStatus.addUid(builder, uidOffset);
    return ListUserStatus.endListUserStatus(builder);
  }

  public static void startListUserStatus(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addUid(FlatBufferBuilder builder, int uidOffset) { builder.addOffset(0, uidOffset, 0); }
  public static int createUidVector(FlatBufferBuilder builder, long[] data) { builder.startVector(8, data.length, 8); for (int i = data.length - 1; i >= 0; i--) builder.addLong(data[i]); return builder.endVector(); }
  public static void startUidVector(FlatBufferBuilder builder, int numElems) { builder.startVector(8, numElems, 8); }
  public static void addStatus(FlatBufferBuilder builder, int statusOffset) { builder.addOffset(1, statusOffset, 0); }
  public static int createStatusVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startStatusVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endListUserStatus(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

