// automatically generated by the FlatBuffers compiler, do not modify

package vn.com.vng.gsmobile.casino.flatbuffers;

public final class LobbyType {
  private LobbyType() { }
  public static final byte None = 0;
  public static final byte Lobby_1 = 1;
  public static final byte Lobby_2 = 2;
  public static final byte Lobby_3 = 3;
  public static final byte Lobby_4 = 4;
  public static final byte Lobby_5 = 5;
  public static final byte Lobby_6 = 6;

  public static final String[] names = { "None", "Lobby_1", "Lobby_2", "Lobby_3", "Lobby_4", "Lobby_5", "Lobby_6", };

  public static String name(int e) { return names[e]; }
}

