// automatically generated by the FlatBuffers compiler, do not modify

package vn.com.vng.gsmobile.casino.flatbuffers;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class LobbyCondition extends Table {
  public static LobbyCondition getRootAsLobbyCondition(ByteBuffer _bb) { return getRootAsLobbyCondition(_bb, new LobbyCondition()); }
  public static LobbyCondition getRootAsLobbyCondition(ByteBuffer _bb, LobbyCondition obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public LobbyCondition __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public int game() { int o = __offset(4); return o != 0 ? bb.get(o + bb_pos) & 0xFF : 0; }
  public boolean mutateGame(int game) { int o = __offset(4); if (o != 0) { bb.put(o + bb_pos, (byte)game); return true; } else { return false; } }
  public int unlockedLobby() { int o = __offset(6); return o != 0 ? bb.get(o + bb_pos) & 0xFF : 0; }
  public boolean mutateUnlockedLobby(int unlocked_lobby) { int o = __offset(6); if (o != 0) { bb.put(o + bb_pos, (byte)unlocked_lobby); return true; } else { return false; } }

  public static int createLobbyCondition(FlatBufferBuilder builder,
      int game,
      int unlocked_lobby) {
    builder.startObject(2);
    LobbyCondition.addUnlockedLobby(builder, unlocked_lobby);
    LobbyCondition.addGame(builder, game);
    return LobbyCondition.endLobbyCondition(builder);
  }

  public static void startLobbyCondition(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addGame(FlatBufferBuilder builder, int game) { builder.addByte(0, (byte)game, 0); }
  public static void addUnlockedLobby(FlatBufferBuilder builder, int unlockedLobby) { builder.addByte(1, (byte)unlockedLobby, 0); }
  public static int endLobbyCondition(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

