// automatically generated by the FlatBuffers compiler, do not modify

package vn.com.vng.gsmobile.casino.flatbuffers;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class LotteryItemInfo extends Table {
  public static LotteryItemInfo getRootAsLotteryItemInfo(ByteBuffer _bb) { return getRootAsLotteryItemInfo(_bb, new LotteryItemInfo()); }
  public static LotteryItemInfo getRootAsLotteryItemInfo(ByteBuffer _bb, LotteryItemInfo obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public LotteryItemInfo __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public String itemName() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer itemNameAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public int itemType() { int o = __offset(6); return o != 0 ? bb.get(o + bb_pos) & 0xFF : 0; }
  public boolean mutateItemType(int item_type) { int o = __offset(6); if (o != 0) { bb.put(o + bb_pos, (byte)item_type); return true; } else { return false; } }
  public long count() { int o = __offset(8); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0; }
  public boolean mutateCount(long count) { int o = __offset(8); if (o != 0) { bb.putInt(o + bb_pos, (int)count); return true; } else { return false; } }

  public static int createLotteryItemInfo(FlatBufferBuilder builder,
      int item_nameOffset,
      int item_type,
      long count) {
    builder.startObject(3);
    LotteryItemInfo.addCount(builder, count);
    LotteryItemInfo.addItemName(builder, item_nameOffset);
    LotteryItemInfo.addItemType(builder, item_type);
    return LotteryItemInfo.endLotteryItemInfo(builder);
  }

  public static void startLotteryItemInfo(FlatBufferBuilder builder) { builder.startObject(3); }
  public static void addItemName(FlatBufferBuilder builder, int itemNameOffset) { builder.addOffset(0, itemNameOffset, 0); }
  public static void addItemType(FlatBufferBuilder builder, int itemType) { builder.addByte(1, (byte)itemType, 0); }
  public static void addCount(FlatBufferBuilder builder, long count) { builder.addInt(2, (int)count, 0); }
  public static int endLotteryItemInfo(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

