// automatically generated by the FlatBuffers compiler, do not modify

package vn.com.vng.gsmobile.casino.flatbuffers;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class MailInfo extends Table {
  public static MailInfo getRootAsMailInfo(ByteBuffer _bb) { return getRootAsMailInfo(_bb, new MailInfo()); }
  public static MailInfo getRootAsMailInfo(ByteBuffer _bb, MailInfo obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public MailInfo __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public String id() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer idAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public vn.com.vng.gsmobile.casino.flatbuffers.SimpleProfile from() { return from(new vn.com.vng.gsmobile.casino.flatbuffers.SimpleProfile()); }
  public vn.com.vng.gsmobile.casino.flatbuffers.SimpleProfile from(vn.com.vng.gsmobile.casino.flatbuffers.SimpleProfile obj) { int o = __offset(6); return o != 0 ? obj.__init(__indirect(o + bb_pos), bb) : null; }
  public String shortMess() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer shortMessAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public long time() { int o = __offset(10); return o != 0 ? bb.getLong(o + bb_pos) : 0; }
  public boolean mutateTime(long time) { int o = __offset(10); if (o != 0) { bb.putLong(o + bb_pos, time); return true; } else { return false; } }
  public int isRead() { int o = __offset(12); return o != 0 ? bb.get(o + bb_pos) & 0xFF : 0; }
  public boolean mutateIsRead(int is_read) { int o = __offset(12); if (o != 0) { bb.put(o + bb_pos, (byte)is_read); return true; } else { return false; } }
  public int mailType() { int o = __offset(14); return o != 0 ? bb.get(o + bb_pos) & 0xFF : 0; }
  public boolean mutateMailType(int mail_type) { int o = __offset(14); if (o != 0) { bb.put(o + bb_pos, (byte)mail_type); return true; } else { return false; } }

  public static int createMailInfo(FlatBufferBuilder builder,
      int idOffset,
      int fromOffset,
      int short_messOffset,
      long time,
      int is_read,
      int mail_type) {
    builder.startObject(6);
    MailInfo.addTime(builder, time);
    MailInfo.addShortMess(builder, short_messOffset);
    MailInfo.addFrom(builder, fromOffset);
    MailInfo.addId(builder, idOffset);
    MailInfo.addMailType(builder, mail_type);
    MailInfo.addIsRead(builder, is_read);
    return MailInfo.endMailInfo(builder);
  }

  public static void startMailInfo(FlatBufferBuilder builder) { builder.startObject(6); }
  public static void addId(FlatBufferBuilder builder, int idOffset) { builder.addOffset(0, idOffset, 0); }
  public static void addFrom(FlatBufferBuilder builder, int fromOffset) { builder.addOffset(1, fromOffset, 0); }
  public static void addShortMess(FlatBufferBuilder builder, int shortMessOffset) { builder.addOffset(2, shortMessOffset, 0); }
  public static void addTime(FlatBufferBuilder builder, long time) { builder.addLong(3, time, 0); }
  public static void addIsRead(FlatBufferBuilder builder, int isRead) { builder.addByte(4, (byte)isRead, 0); }
  public static void addMailType(FlatBufferBuilder builder, int mailType) { builder.addByte(5, (byte)mailType, 0); }
  public static int endMailInfo(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

