// automatically generated by the FlatBuffers compiler, do not modify

package vn.com.vng.gsmobile.casino.flatbuffers;

public final class MailType {
  private MailType() { }
  public static final byte None = 0;
  public static final byte MailUser = 1;
  public static final byte MailSystem = 2;

  public static final String[] names = { "None", "MailUser", "MailSystem", };

  public static String name(int e) { return names[e]; }
}

