// automatically generated by the FlatBuffers compiler, do not modify

package vn.com.vng.gsmobile.casino.flatbuffers;

public final class MauBinhType {
  private MauBinhType() { }
  public static final byte None = -1;
  public static final byte Normal = 0;
  public static final byte BinhLung = 1;
  public static final byte MauThau = 2;
  public static final byte Doi = 3;
  public static final byte Thu = 4;
  public static final byte Sam = 5;
  public static final byte SamChi3 = 6;
  public static final byte Sanh = 7;
  public static final byte Thung = 8;
  public static final byte CuLu = 9;
  public static final byte CuLuChi2 = 10;
  public static final byte TuQuy = 11;
  public static final byte TuQuyChi2 = 12;
  public static final byte ThungPhaSanh = 13;
  public static final byte ThungPhaSanhChi2 = 14;
  public static final byte LucPheBon = 15;
  public static final byte NamDoiMotSam = 16;
  public static final byte BonSamCo = 17;
  public static final byte BaSanh = 18;
  public static final byte BaThung = 19;
  public static final byte DongHoa2 = 20;
  public static final byte DongHoa1 = 21;
  public static final byte SanhRong = 22;
  public static final byte RongCuon = 23;

  public static final String[] names = { "None", "Normal", "BinhLung", "MauThau", "Doi", "Thu", "Sam", "SamChi3", "Sanh", "Thung", "CuLu", "CuLuChi2", "TuQuy", "TuQuyChi2", "ThungPhaSanh", "ThungPhaSanhChi2", "LucPheBon", "NamDoiMotSam", "BonSamCo", "BaSanh", "BaThung", "DongHoa2", "DongHoa1", "SanhRong", "RongCuon", };

  public static String name(int e) { return names[e - None]; }
}

