// automatically generated by the FlatBuffers compiler, do not modify

package vn.com.vng.gsmobile.casino.flatbuffers;

public final class MBResultStatus {
  private MBResultStatus() { }
  public static final byte Normal = 0;
  public static final byte BinhLung = 1;
  public static final byte MauBinh = 2;
  public static final byte SapBaChi = 3;
  public static final byte BatSapBaChi = 4;
  public static final byte BatSapLang = 5;

  public static final String[] names = { "Normal", "BinhLung", "MauBinh", "SapBaChi", "BatSapBaChi", "BatSapLang", };

  public static String name(int e) { return names[e]; }
}

