// automatically generated by the FlatBuffers compiler, do not modify

package vn.com.vng.gsmobile.casino.flatbuffers;

public final class MBShowType {
  private MBShowType() { }
  public static final byte None = 0;
  public static final byte So_Chi = 1;
  public static final byte Bao_Binh = 2;

  public static final String[] names = { "None", "So_Chi", "Bao_Binh", };

  public static String name(int e) { return names[e]; }
}

