// automatically generated by the FlatBuffers compiler, do not modify

package vn.com.vng.gsmobile.casino.flatbuffers;

public final class PayChannel {
  private PayChannel() { }
  public static final byte App = 0;
  public static final byte Web = 1;

  public static final String[] names = { "App", "Web", };

  public static String name(int e) { return names[e]; }
}

