// automatically generated by the FlatBuffers compiler, do not modify

package vn.com.vng.gsmobile.casino.flatbuffers;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class PlayerTLMNCardInfo extends Table {
  public static PlayerTLMNCardInfo getRootAsPlayerTLMNCardInfo(ByteBuffer _bb) { return getRootAsPlayerTLMNCardInfo(_bb, new PlayerTLMNCardInfo()); }
  public static PlayerTLMNCardInfo getRootAsPlayerTLMNCardInfo(ByteBuffer _bb, PlayerTLMNCardInfo obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public PlayerTLMNCardInfo __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public long playerId() { int o = __offset(4); return o != 0 ? bb.getLong(o + bb_pos) : 0; }
  public boolean mutatePlayerId(long player_id) { int o = __offset(4); if (o != 0) { bb.putLong(o + bb_pos, player_id); return true; } else { return false; } }
  public int skipped() { int o = __offset(6); return o != 0 ? bb.get(o + bb_pos) & 0xFF : 0; }
  public boolean mutateSkipped(int skipped) { int o = __offset(6); if (o != 0) { bb.put(o + bb_pos, (byte)skipped); return true; } else { return false; } }
  public CardTLMNInfo cards(int j) { return cards(new CardTLMNInfo(), j); }
  public CardTLMNInfo cards(CardTLMNInfo obj, int j) { int o = __offset(8); return o != 0 ? obj.__init(__indirect(__vector(o) + j * 4), bb) : null; }
  public int cardsLength() { int o = __offset(8); return o != 0 ? __vector_len(o) : 0; }

  public static int createPlayerTLMNCardInfo(FlatBufferBuilder builder,
      long player_id,
      int skipped,
      int cardsOffset) {
    builder.startObject(3);
    PlayerTLMNCardInfo.addPlayerId(builder, player_id);
    PlayerTLMNCardInfo.addCards(builder, cardsOffset);
    PlayerTLMNCardInfo.addSkipped(builder, skipped);
    return PlayerTLMNCardInfo.endPlayerTLMNCardInfo(builder);
  }

  public static void startPlayerTLMNCardInfo(FlatBufferBuilder builder) { builder.startObject(3); }
  public static void addPlayerId(FlatBufferBuilder builder, long playerId) { builder.addLong(0, playerId, 0); }
  public static void addSkipped(FlatBufferBuilder builder, int skipped) { builder.addByte(1, (byte)skipped, 0); }
  public static void addCards(FlatBufferBuilder builder, int cardsOffset) { builder.addOffset(2, cardsOffset, 0); }
  public static int createCardsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startCardsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endPlayerTLMNCardInfo(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

