// automatically generated by the FlatBuffers compiler, do not modify

package vn.com.vng.gsmobile.casino.flatbuffers;

public final class QuitState {
  private QuitState() { }
  public static final byte QUIT_REGISTER = 0;
  public static final byte QUIT_UNREGISTER = 1;
  public static final byte QUIT_ACCEPT = 2;
  public static final byte QUIT_REJECT = 3;
  public static final byte QUIT_NOT_ENOUGH_MONEY = 4;
  public static final byte QUIT_POOR_CONNECTION = 5;

  public static final String[] names = { "QUIT_REGISTER", "QUIT_UNREGISTER", "QUIT_ACCEPT", "QUIT_REJECT", "QUIT_NOT_ENOUGH_MONEY", "QUIT_POOR_CONNECTION", };

  public static String name(int e) { return names[e]; }
}

