// automatically generated by the FlatBuffers compiler, do not modify

package vn.com.vng.gsmobile.casino.flatbuffers;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class RankUser extends Table {
  public static RankUser getRootAsRankUser(ByteBuffer _bb) { return getRootAsRankUser(_bb, new RankUser()); }
  public static RankUser getRootAsRankUser(ByteBuffer _bb, RankUser obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public RankUser __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public vn.com.vng.gsmobile.casino.flatbuffers.UserInfo user() { return user(new vn.com.vng.gsmobile.casino.flatbuffers.UserInfo()); }
  public vn.com.vng.gsmobile.casino.flatbuffers.UserInfo user(vn.com.vng.gsmobile.casino.flatbuffers.UserInfo obj) { int o = __offset(4); return o != 0 ? obj.__init(__indirect(o + bb_pos), bb) : null; }
  public long score() { int o = __offset(6); return o != 0 ? bb.getLong(o + bb_pos) : 0; }
  public boolean mutateScore(long score) { int o = __offset(6); if (o != 0) { bb.putLong(o + bb_pos, score); return true; } else { return false; } }

  public static int createRankUser(FlatBufferBuilder builder,
      int userOffset,
      long score) {
    builder.startObject(2);
    RankUser.addScore(builder, score);
    RankUser.addUser(builder, userOffset);
    return RankUser.endRankUser(builder);
  }

  public static void startRankUser(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addUser(FlatBufferBuilder builder, int userOffset) { builder.addOffset(0, userOffset, 0); }
  public static void addScore(FlatBufferBuilder builder, long score) { builder.addLong(1, score, 0); }
  public static int endRankUser(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

