// automatically generated by the FlatBuffers compiler, do not modify

package vn.com.vng.gsmobile.casino.flatbuffers;

public final class RankType {
  private RankType() { }
  public static final byte RankNone = 0;
  public static final byte RankGlobalLevel = 1;
  public static final byte RankGlobalMoney = 2;
  public static final byte RankGlobalPlayCnt = 3;
  public static final byte RankFriendLevel = 11;
  public static final byte RankFriendMoney = 12;
  public static final byte RankGameCao = 21;
  public static final byte RankGameTLMN = 22;
  public static final byte RankGameTala = 23;
  public static final byte RankGameMauBinh = 24;
  public static final byte RankEventDailyCao = 41;
  public static final byte RankEventDailyTLMN = 42;
  public static final byte RankEventDailyTala = 43;
  public static final byte RankEventDailyMauBinh = 44;

  public static final String[] names = { "RankNone", "RankGlobalLevel", "RankGlobalMoney", "RankGlobalPlayCnt", "", "", "", "", "", "", "", "RankFriendLevel", "RankFriendMoney", "", "", "", "", "", "", "", "", "RankGameCao", "RankGameTLMN", "RankGameTala", "RankGameMauBinh", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "RankEventDailyCao", "RankEventDailyTLMN", "RankEventDailyTala", "RankEventDailyMauBinh", };

  public static String name(int e) { return names[e]; }
}

