// automatically generated by the FlatBuffers compiler, do not modify

package vn.com.vng.gsmobile.casino.flatbuffers;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class RoomUpdateInfo extends Table {
  public static RoomUpdateInfo getRootAsRoomUpdateInfo(ByteBuffer _bb) { return getRootAsRoomUpdateInfo(_bb, new RoomUpdateInfo()); }
  public static RoomUpdateInfo getRootAsRoomUpdateInfo(ByteBuffer _bb, RoomUpdateInfo obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public RoomUpdateInfo __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public long roomId() { int o = __offset(4); return o != 0 ? bb.getLong(o + bb_pos) : 0; }
  public boolean mutateRoomId(long room_id) { int o = __offset(4); if (o != 0) { bb.putLong(o + bb_pos, room_id); return true; } else { return false; } }
  public int state() { int o = __offset(6); return o != 0 ? bb.get(o + bb_pos) & 0xFF : 0; }
  public boolean mutateState(int state) { int o = __offset(6); if (o != 0) { bb.put(o + bb_pos, (byte)state); return true; } else { return false; } }
  public long timeRemaining() { int o = __offset(8); return o != 0 ? bb.getLong(o + bb_pos) : 0; }
  public boolean mutateTimeRemaining(long time_remaining) { int o = __offset(8); if (o != 0) { bb.putLong(o + bb_pos, time_remaining); return true; } else { return false; } }
  public RoomDetailInfo detail() { return detail(new RoomDetailInfo()); }
  public RoomDetailInfo detail(RoomDetailInfo obj) { int o = __offset(10); return o != 0 ? obj.__init(__indirect(o + bb_pos), bb) : null; }

  public static int createRoomUpdateInfo(FlatBufferBuilder builder,
      long room_id,
      int state,
      long time_remaining,
      int detailOffset) {
    builder.startObject(4);
    RoomUpdateInfo.addTimeRemaining(builder, time_remaining);
    RoomUpdateInfo.addRoomId(builder, room_id);
    RoomUpdateInfo.addDetail(builder, detailOffset);
    RoomUpdateInfo.addState(builder, state);
    return RoomUpdateInfo.endRoomUpdateInfo(builder);
  }

  public static void startRoomUpdateInfo(FlatBufferBuilder builder) { builder.startObject(4); }
  public static void addRoomId(FlatBufferBuilder builder, long roomId) { builder.addLong(0, roomId, 0); }
  public static void addState(FlatBufferBuilder builder, int state) { builder.addByte(1, (byte)state, 0); }
  public static void addTimeRemaining(FlatBufferBuilder builder, long timeRemaining) { builder.addLong(2, timeRemaining, 0); }
  public static void addDetail(FlatBufferBuilder builder, int detailOffset) { builder.addOffset(3, detailOffset, 0); }
  public static int endRoomUpdateInfo(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

