// automatically generated by the FlatBuffers compiler, do not modify

package vn.com.vng.gsmobile.casino.flatbuffers;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class RoomResponse extends Table {
  public static RoomResponse getRootAsRoomResponse(ByteBuffer _bb) { return getRootAsRoomResponse(_bb, new RoomResponse()); }
  public static RoomResponse getRootAsRoomResponse(ByteBuffer _bb, RoomResponse obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public RoomResponse __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public String reqToken() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer reqTokenAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public int lobbyType() { int o = __offset(6); return o != 0 ? bb.get(o + bb_pos) & 0xFF : 0; }
  public boolean mutateLobbyType(int lobby_type) { int o = __offset(6); if (o != 0) { bb.put(o + bb_pos, (byte)lobby_type); return true; } else { return false; } }
  public RoomInfo room() { return room(new RoomInfo()); }
  public RoomInfo room(RoomInfo obj) { int o = __offset(8); return o != 0 ? obj.__init(__indirect(o + bb_pos), bb) : null; }

  public static int createRoomResponse(FlatBufferBuilder builder,
      int req_tokenOffset,
      int lobby_type,
      int roomOffset) {
    builder.startObject(3);
    RoomResponse.addRoom(builder, roomOffset);
    RoomResponse.addReqToken(builder, req_tokenOffset);
    RoomResponse.addLobbyType(builder, lobby_type);
    return RoomResponse.endRoomResponse(builder);
  }

  public static void startRoomResponse(FlatBufferBuilder builder) { builder.startObject(3); }
  public static void addReqToken(FlatBufferBuilder builder, int reqTokenOffset) { builder.addOffset(0, reqTokenOffset, 0); }
  public static void addLobbyType(FlatBufferBuilder builder, int lobbyType) { builder.addByte(1, (byte)lobbyType, 0); }
  public static void addRoom(FlatBufferBuilder builder, int roomOffset) { builder.addOffset(2, roomOffset, 0); }
  public static int endRoomResponse(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

