// automatically generated by the FlatBuffers compiler, do not modify

package vn.com.vng.gsmobile.casino.flatbuffers;

public final class ShopItemState {
  private ShopItemState() { }
  public static final byte State_Disabled = 0;
  public static final byte State_CommingSoon = 1;
  public static final byte State_Selling = 2;

  public static final String[] names = { "State_Disabled", "State_CommingSoon", "State_Selling", };

  public static String name(int e) { return names[e]; }
}

