// automatically generated by the FlatBuffers compiler, do not modify

package vn.com.vng.gsmobile.casino.flatbuffers;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class ShopHistoryItem extends Table {
  public static ShopHistoryItem getRootAsShopHistoryItem(ByteBuffer _bb) { return getRootAsShopHistoryItem(_bb, new ShopHistoryItem()); }
  public static ShopHistoryItem getRootAsShopHistoryItem(ByteBuffer _bb, ShopHistoryItem obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public ShopHistoryItem __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public long itemId() { int o = __offset(4); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0; }
  public boolean mutateItemId(long item_id) { int o = __offset(4); if (o != 0) { bb.putInt(o + bb_pos, (int)item_id); return true; } else { return false; } }
  public long buyTime() { int o = __offset(6); return o != 0 ? bb.getLong(o + bb_pos) : 0; }
  public boolean mutateBuyTime(long buy_time) { int o = __offset(6); if (o != 0) { bb.putLong(o + bb_pos, buy_time); return true; } else { return false; } }
  public long coinOrigin() { int o = __offset(8); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0; }
  public boolean mutateCoinOrigin(long coin_origin) { int o = __offset(8); if (o != 0) { bb.putInt(o + bb_pos, (int)coin_origin); return true; } else { return false; } }
  public long coinPromo() { int o = __offset(10); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0; }
  public boolean mutateCoinPromo(long coin_promo) { int o = __offset(10); if (o != 0) { bb.putInt(o + bb_pos, (int)coin_promo); return true; } else { return false; } }
  public int channel() { int o = __offset(12); return o != 0 ? bb.get(o + bb_pos) & 0xFF : 0; }
  public boolean mutateChannel(int channel) { int o = __offset(12); if (o != 0) { bb.put(o + bb_pos, (byte)channel); return true; } else { return false; } }

  public static int createShopHistoryItem(FlatBufferBuilder builder,
      long item_id,
      long buy_time,
      long coin_origin,
      long coin_promo,
      int channel) {
    builder.startObject(5);
    ShopHistoryItem.addBuyTime(builder, buy_time);
    ShopHistoryItem.addCoinPromo(builder, coin_promo);
    ShopHistoryItem.addCoinOrigin(builder, coin_origin);
    ShopHistoryItem.addItemId(builder, item_id);
    ShopHistoryItem.addChannel(builder, channel);
    return ShopHistoryItem.endShopHistoryItem(builder);
  }

  public static void startShopHistoryItem(FlatBufferBuilder builder) { builder.startObject(5); }
  public static void addItemId(FlatBufferBuilder builder, long itemId) { builder.addInt(0, (int)itemId, 0); }
  public static void addBuyTime(FlatBufferBuilder builder, long buyTime) { builder.addLong(1, buyTime, 0); }
  public static void addCoinOrigin(FlatBufferBuilder builder, long coinOrigin) { builder.addInt(2, (int)coinOrigin, 0); }
  public static void addCoinPromo(FlatBufferBuilder builder, long coinPromo) { builder.addInt(3, (int)coinPromo, 0); }
  public static void addChannel(FlatBufferBuilder builder, int channel) { builder.addByte(4, (byte)channel, 0); }
  public static int endShopHistoryItem(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

