// automatically generated by the FlatBuffers compiler, do not modify

package vn.com.vng.gsmobile.casino.flatbuffers;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class ShopItem extends Table {
  public static ShopItem getRootAsShopItem(ByteBuffer _bb) { return getRootAsShopItem(_bb, new ShopItem()); }
  public static ShopItem getRootAsShopItem(ByteBuffer _bb, ShopItem obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public ShopItem __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public long shopId() { int o = __offset(4); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0; }
  public boolean mutateShopId(long shop_id) { int o = __offset(4); if (o != 0) { bb.putInt(o + bb_pos, (int)shop_id); return true; } else { return false; } }
  public long itemValueBase() { int o = __offset(6); return o != 0 ? bb.getLong(o + bb_pos) : 0; }
  public boolean mutateItemValueBase(long item_value_base) { int o = __offset(6); if (o != 0) { bb.putLong(o + bb_pos, item_value_base); return true; } else { return false; } }
  public long itemValue() { int o = __offset(8); return o != 0 ? bb.getLong(o + bb_pos) : 0; }
  public boolean mutateItemValue(long item_value) { int o = __offset(8); if (o != 0) { bb.putLong(o + bb_pos, item_value); return true; } else { return false; } }
  public int itemType() { int o = __offset(10); return o != 0 ? bb.get(o + bb_pos) & 0xFF : 0; }
  public boolean mutateItemType(int item_type) { int o = __offset(10); if (o != 0) { bb.put(o + bb_pos, (byte)item_type); return true; } else { return false; } }
  public int costType() { int o = __offset(12); return o != 0 ? bb.get(o + bb_pos) & 0xFF : 0; }
  public boolean mutateCostType(int cost_type) { int o = __offset(12); if (o != 0) { bb.put(o + bb_pos, (byte)cost_type); return true; } else { return false; } }
  public long costValueBase() { int o = __offset(14); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0; }
  public boolean mutateCostValueBase(long cost_value_base) { int o = __offset(14); if (o != 0) { bb.putInt(o + bb_pos, (int)cost_value_base); return true; } else { return false; } }
  public long costValue() { int o = __offset(16); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0; }
  public boolean mutateCostValue(long cost_value) { int o = __offset(16); if (o != 0) { bb.putInt(o + bb_pos, (int)cost_value); return true; } else { return false; } }
  public long costShow() { int o = __offset(18); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0; }
  public boolean mutateCostShow(long cost_show) { int o = __offset(18); if (o != 0) { bb.putInt(o + bb_pos, (int)cost_show); return true; } else { return false; } }
  public String costCurrency() { int o = __offset(20); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer costCurrencyAsByteBuffer() { return __vector_as_bytebuffer(20, 1); }
  public long promo() { int o = __offset(22); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0; }
  public boolean mutatePromo(long promo) { int o = __offset(22); if (o != 0) { bb.putInt(o + bb_pos, (int)promo); return true; } else { return false; } }
  public int discount() { int o = __offset(24); return o != 0 ? bb.get(o + bb_pos) & 0xFF : 0; }
  public boolean mutateDiscount(int discount) { int o = __offset(24); if (o != 0) { bb.put(o + bb_pos, (byte)discount); return true; } else { return false; } }
  public long eventId() { int o = __offset(26); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0; }
  public boolean mutateEventId(long event_id) { int o = __offset(26); if (o != 0) { bb.putInt(o + bb_pos, (int)event_id); return true; } else { return false; } }
  public String eventDescription() { int o = __offset(28); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer eventDescriptionAsByteBuffer() { return __vector_as_bytebuffer(28, 1); }
  public int star() { int o = __offset(30); return o != 0 ? bb.getShort(o + bb_pos) & 0xFFFF : 0; }
  public boolean mutateStar(int star) { int o = __offset(30); if (o != 0) { bb.putShort(o + bb_pos, (short)star); return true; } else { return false; } }
  public int state() { int o = __offset(32); return o != 0 ? bb.get(o + bb_pos) & 0xFF : 0; }
  public boolean mutateState(int state) { int o = __offset(32); if (o != 0) { bb.put(o + bb_pos, (byte)state); return true; } else { return false; } }
  public String paymentSku() { int o = __offset(34); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer paymentSkuAsByteBuffer() { return __vector_as_bytebuffer(34, 1); }
  public String googleSku() { int o = __offset(36); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer googleSkuAsByteBuffer() { return __vector_as_bytebuffer(36, 1); }
  public String appleSku() { int o = __offset(38); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer appleSkuAsByteBuffer() { return __vector_as_bytebuffer(38, 1); }

  public static int createShopItem(FlatBufferBuilder builder,
      long shop_id,
      long item_value_base,
      long item_value,
      int item_type,
      int cost_type,
      long cost_value_base,
      long cost_value,
      long cost_show,
      int cost_currencyOffset,
      long promo,
      int discount,
      long event_id,
      int event_descriptionOffset,
      int star,
      int state,
      int payment_skuOffset,
      int google_skuOffset,
      int apple_skuOffset) {
    builder.startObject(18);
    ShopItem.addItemValue(builder, item_value);
    ShopItem.addItemValueBase(builder, item_value_base);
    ShopItem.addAppleSku(builder, apple_skuOffset);
    ShopItem.addGoogleSku(builder, google_skuOffset);
    ShopItem.addPaymentSku(builder, payment_skuOffset);
    ShopItem.addEventDescription(builder, event_descriptionOffset);
    ShopItem.addEventId(builder, event_id);
    ShopItem.addPromo(builder, promo);
    ShopItem.addCostCurrency(builder, cost_currencyOffset);
    ShopItem.addCostShow(builder, cost_show);
    ShopItem.addCostValue(builder, cost_value);
    ShopItem.addCostValueBase(builder, cost_value_base);
    ShopItem.addShopId(builder, shop_id);
    ShopItem.addStar(builder, star);
    ShopItem.addState(builder, state);
    ShopItem.addDiscount(builder, discount);
    ShopItem.addCostType(builder, cost_type);
    ShopItem.addItemType(builder, item_type);
    return ShopItem.endShopItem(builder);
  }

  public static void startShopItem(FlatBufferBuilder builder) { builder.startObject(18); }
  public static void addShopId(FlatBufferBuilder builder, long shopId) { builder.addInt(0, (int)shopId, 0); }
  public static void addItemValueBase(FlatBufferBuilder builder, long itemValueBase) { builder.addLong(1, itemValueBase, 0); }
  public static void addItemValue(FlatBufferBuilder builder, long itemValue) { builder.addLong(2, itemValue, 0); }
  public static void addItemType(FlatBufferBuilder builder, int itemType) { builder.addByte(3, (byte)itemType, 0); }
  public static void addCostType(FlatBufferBuilder builder, int costType) { builder.addByte(4, (byte)costType, 0); }
  public static void addCostValueBase(FlatBufferBuilder builder, long costValueBase) { builder.addInt(5, (int)costValueBase, 0); }
  public static void addCostValue(FlatBufferBuilder builder, long costValue) { builder.addInt(6, (int)costValue, 0); }
  public static void addCostShow(FlatBufferBuilder builder, long costShow) { builder.addInt(7, (int)costShow, 0); }
  public static void addCostCurrency(FlatBufferBuilder builder, int costCurrencyOffset) { builder.addOffset(8, costCurrencyOffset, 0); }
  public static void addPromo(FlatBufferBuilder builder, long promo) { builder.addInt(9, (int)promo, 0); }
  public static void addDiscount(FlatBufferBuilder builder, int discount) { builder.addByte(10, (byte)discount, 0); }
  public static void addEventId(FlatBufferBuilder builder, long eventId) { builder.addInt(11, (int)eventId, 0); }
  public static void addEventDescription(FlatBufferBuilder builder, int eventDescriptionOffset) { builder.addOffset(12, eventDescriptionOffset, 0); }
  public static void addStar(FlatBufferBuilder builder, int star) { builder.addShort(13, (short)star, 0); }
  public static void addState(FlatBufferBuilder builder, int state) { builder.addByte(14, (byte)state, 0); }
  public static void addPaymentSku(FlatBufferBuilder builder, int paymentSkuOffset) { builder.addOffset(15, paymentSkuOffset, 0); }
  public static void addGoogleSku(FlatBufferBuilder builder, int googleSkuOffset) { builder.addOffset(16, googleSkuOffset, 0); }
  public static void addAppleSku(FlatBufferBuilder builder, int appleSkuOffset) { builder.addOffset(17, appleSkuOffset, 0); }
  public static int endShopItem(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

