// automatically generated by the FlatBuffers compiler, do not modify

package vn.com.vng.gsmobile.casino.flatbuffers;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class SimpleProfile extends Table {
  public static SimpleProfile getRootAsSimpleProfile(ByteBuffer _bb) { return getRootAsSimpleProfile(_bb, new SimpleProfile()); }
  public static SimpleProfile getRootAsSimpleProfile(ByteBuffer _bb, SimpleProfile obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public SimpleProfile __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public long uid() { int o = __offset(4); return o != 0 ? bb.getLong(o + bb_pos) : 0; }
  public boolean mutateUid(long uid) { int o = __offset(4); if (o != 0) { bb.putLong(o + bb_pos, uid); return true; } else { return false; } }
  public String name() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer nameAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public String avatar() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer avatarAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }

  public static int createSimpleProfile(FlatBufferBuilder builder,
      long uid,
      int nameOffset,
      int avatarOffset) {
    builder.startObject(3);
    SimpleProfile.addUid(builder, uid);
    SimpleProfile.addAvatar(builder, avatarOffset);
    SimpleProfile.addName(builder, nameOffset);
    return SimpleProfile.endSimpleProfile(builder);
  }

  public static void startSimpleProfile(FlatBufferBuilder builder) { builder.startObject(3); }
  public static void addUid(FlatBufferBuilder builder, long uid) { builder.addLong(0, uid, 0); }
  public static void addName(FlatBufferBuilder builder, int nameOffset) { builder.addOffset(1, nameOffset, 0); }
  public static void addAvatar(FlatBufferBuilder builder, int avatarOffset) { builder.addOffset(2, avatarOffset, 0); }
  public static int endSimpleProfile(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

