// automatically generated by the FlatBuffers compiler, do not modify

package vn.com.vng.gsmobile.casino.flatbuffers;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class UserCondition extends Table {
  public static UserCondition getRootAsUserCondition(ByteBuffer _bb) { return getRootAsUserCondition(_bb, new UserCondition()); }
  public static UserCondition getRootAsUserCondition(ByteBuffer _bb, UserCondition obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public UserCondition __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public long uid() { int o = __offset(4); return o != 0 ? bb.getLong(o + bb_pos) : 0; }
  public boolean mutateUid(long uid) { int o = __offset(4); if (o != 0) { bb.putLong(o + bb_pos, uid); return true; } else { return false; } }
  public LobbyCondition gameLobby(int j) { return gameLobby(new LobbyCondition(), j); }
  public LobbyCondition gameLobby(LobbyCondition obj, int j) { int o = __offset(6); return o != 0 ? obj.__init(__indirect(__vector(o) + j * 4), bb) : null; }
  public int gameLobbyLength() { int o = __offset(6); return o != 0 ? __vector_len(o) : 0; }

  public static int createUserCondition(FlatBufferBuilder builder,
      long uid,
      int game_lobbyOffset) {
    builder.startObject(2);
    UserCondition.addUid(builder, uid);
    UserCondition.addGameLobby(builder, game_lobbyOffset);
    return UserCondition.endUserCondition(builder);
  }

  public static void startUserCondition(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addUid(FlatBufferBuilder builder, long uid) { builder.addLong(0, uid, 0); }
  public static void addGameLobby(FlatBufferBuilder builder, int gameLobbyOffset) { builder.addOffset(1, gameLobbyOffset, 0); }
  public static int createGameLobbyVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startGameLobbyVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endUserCondition(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

