// automatically generated by the FlatBuffers compiler, do not modify

package vn.com.vng.gsmobile.casino.flatbuffers;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class UserInfo extends Table {
  public static UserInfo getRootAsUserInfo(ByteBuffer _bb) { return getRootAsUserInfo(_bb, new UserInfo()); }
  public static UserInfo getRootAsUserInfo(ByteBuffer _bb, UserInfo obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public UserInfo __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public long uid() { int o = __offset(4); return o != 0 ? bb.getLong(o + bb_pos) : 0; }
  public boolean mutateUid(long uid) { int o = __offset(4); if (o != 0) { bb.putLong(o + bb_pos, uid); return true; } else { return false; } }
  public String name() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer nameAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public String avatar() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer avatarAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public int status() { int o = __offset(10); return o != 0 ? bb.get(o + bb_pos) & 0xFF : 0; }
  public boolean mutateStatus(int status) { int o = __offset(10); if (o != 0) { bb.put(o + bb_pos, (byte)status); return true; } else { return false; } }
  public int accType() { int o = __offset(12); return o != 0 ? bb.get(o + bb_pos) & 0xFF : 0; }
  public boolean mutateAccType(int acc_type) { int o = __offset(12); if (o != 0) { bb.put(o + bb_pos, (byte)acc_type); return true; } else { return false; } }
  public int vip() { int o = __offset(14); return o != 0 ? bb.get(o + bb_pos) & 0xFF : 0; }
  public boolean mutateVip(int vip) { int o = __offset(14); if (o != 0) { bb.put(o + bb_pos, (byte)vip); return true; } else { return false; } }
  public long coin() { int o = __offset(16); return o != 0 ? bb.getLong(o + bb_pos) : 0; }
  public boolean mutateCoin(long coin) { int o = __offset(16); if (o != 0) { bb.putLong(o + bb_pos, coin); return true; } else { return false; } }
  public int level() { int o = __offset(18); return o != 0 ? bb.getShort(o + bb_pos) & 0xFFFF : 0; }
  public boolean mutateLevel(int level) { int o = __offset(18); if (o != 0) { bb.putShort(o + bb_pos, (short)level); return true; } else { return false; } }
  public UserInfoDetail detail() { return detail(new UserInfoDetail()); }
  public UserInfoDetail detail(UserInfoDetail obj) { int o = __offset(20); return o != 0 ? obj.__init(__indirect(o + bb_pos), bb) : null; }

  public static int createUserInfo(FlatBufferBuilder builder,
      long uid,
      int nameOffset,
      int avatarOffset,
      int status,
      int acc_type,
      int vip,
      long coin,
      int level,
      int detailOffset) {
    builder.startObject(9);
    UserInfo.addCoin(builder, coin);
    UserInfo.addUid(builder, uid);
    UserInfo.addDetail(builder, detailOffset);
    UserInfo.addAvatar(builder, avatarOffset);
    UserInfo.addName(builder, nameOffset);
    UserInfo.addLevel(builder, level);
    UserInfo.addVip(builder, vip);
    UserInfo.addAccType(builder, acc_type);
    UserInfo.addStatus(builder, status);
    return UserInfo.endUserInfo(builder);
  }

  public static void startUserInfo(FlatBufferBuilder builder) { builder.startObject(9); }
  public static void addUid(FlatBufferBuilder builder, long uid) { builder.addLong(0, uid, 0); }
  public static void addName(FlatBufferBuilder builder, int nameOffset) { builder.addOffset(1, nameOffset, 0); }
  public static void addAvatar(FlatBufferBuilder builder, int avatarOffset) { builder.addOffset(2, avatarOffset, 0); }
  public static void addStatus(FlatBufferBuilder builder, int status) { builder.addByte(3, (byte)status, 0); }
  public static void addAccType(FlatBufferBuilder builder, int accType) { builder.addByte(4, (byte)accType, 0); }
  public static void addVip(FlatBufferBuilder builder, int vip) { builder.addByte(5, (byte)vip, 0); }
  public static void addCoin(FlatBufferBuilder builder, long coin) { builder.addLong(6, coin, 0); }
  public static void addLevel(FlatBufferBuilder builder, int level) { builder.addShort(7, (short)level, 0); }
  public static void addDetail(FlatBufferBuilder builder, int detailOffset) { builder.addOffset(8, detailOffset, 0); }
  public static int endUserInfo(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

