// automatically generated by the FlatBuffers compiler, do not modify

package vn.com.vng.gsmobile.casino.flatbuffers;

public final class UserAccType {
  private UserAccType() { }
  public static final byte None = 0;
  public static final byte Facebook = 1;
  public static final byte Zalo = 2;
  public static final byte Guest = 3;
  public static final byte Zing = 4;

  public static final String[] names = { "None", "Facebook", "Zalo", "Guest", "Zing", };

  public static String name(int e) { return names[e]; }
}

