// automatically generated by the FlatBuffers compiler, do not modify

package vn.com.vng.gsmobile.casino.flatbuffers;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class UserAppSetting extends Table {
  public static UserAppSetting getRootAsUserAppSetting(ByteBuffer _bb) { return getRootAsUserAppSetting(_bb, new UserAppSetting()); }
  public static UserAppSetting getRootAsUserAppSetting(ByteBuffer _bb, UserAppSetting obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public UserAppSetting __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public long uid() { int o = __offset(4); return o != 0 ? bb.getLong(o + bb_pos) : 0; }
  public boolean mutateUid(long uid) { int o = __offset(4); if (o != 0) { bb.putLong(o + bb_pos, uid); return true; } else { return false; } }
  public int sound() { int o = __offset(6); return o != 0 ? bb.get(o + bb_pos) & 0xFF : 1; }
  public boolean mutateSound(int sound) { int o = __offset(6); if (o != 0) { bb.put(o + bb_pos, (byte)sound); return true; } else { return false; } }
  public int music() { int o = __offset(8); return o != 0 ? bb.get(o + bb_pos) & 0xFF : 1; }
  public boolean mutateMusic(int music) { int o = __offset(8); if (o != 0) { bb.put(o + bb_pos, (byte)music); return true; } else { return false; } }
  public int vibrate() { int o = __offset(10); return o != 0 ? bb.get(o + bb_pos) & 0xFF : 1; }
  public boolean mutateVibrate(int vibrate) { int o = __offset(10); if (o != 0) { bb.put(o + bb_pos, (byte)vibrate); return true; } else { return false; } }
  public int receivedInvite() { int o = __offset(12); return o != 0 ? bb.get(o + bb_pos) & 0xFF : 1; }
  public boolean mutateReceivedInvite(int received_invite) { int o = __offset(12); if (o != 0) { bb.put(o + bb_pos, (byte)received_invite); return true; } else { return false; } }

  public static int createUserAppSetting(FlatBufferBuilder builder,
      long uid,
      int sound,
      int music,
      int vibrate,
      int received_invite) {
    builder.startObject(5);
    UserAppSetting.addUid(builder, uid);
    UserAppSetting.addReceivedInvite(builder, received_invite);
    UserAppSetting.addVibrate(builder, vibrate);
    UserAppSetting.addMusic(builder, music);
    UserAppSetting.addSound(builder, sound);
    return UserAppSetting.endUserAppSetting(builder);
  }

  public static void startUserAppSetting(FlatBufferBuilder builder) { builder.startObject(5); }
  public static void addUid(FlatBufferBuilder builder, long uid) { builder.addLong(0, uid, 0); }
  public static void addSound(FlatBufferBuilder builder, int sound) { builder.addByte(1, (byte)sound, 1); }
  public static void addMusic(FlatBufferBuilder builder, int music) { builder.addByte(2, (byte)music, 1); }
  public static void addVibrate(FlatBufferBuilder builder, int vibrate) { builder.addByte(3, (byte)vibrate, 1); }
  public static void addReceivedInvite(FlatBufferBuilder builder, int receivedInvite) { builder.addByte(4, (byte)receivedInvite, 1); }
  public static int endUserAppSetting(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

