// automatically generated by the FlatBuffers compiler, do not modify

package vn.com.vng.gsmobile.casino.flatbuffers;

public final class UserStatus {
  private UserStatus() { }
  public static final byte Offline = 0;
  public static final byte Idle = 1;
  public static final byte On_Lobby = 2;
  public static final byte On_Room_Play = 3;
  public static final byte On_Room_View = 4;

  public static final String[] names = { "Offline", "Idle", "On_Lobby", "On_Room_Play", "On_Room_View", };

  public static String name(int e) { return names[e]; }
}

