// automatically generated by the FlatBuffers compiler, do not modify

package vn.com.vng.gsmobile.casino.flatbuffers;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class VIPInfo extends Table {
  public static VIPInfo getRootAsVIPInfo(ByteBuffer _bb) { return getRootAsVIPInfo(_bb, new VIPInfo()); }
  public static VIPInfo getRootAsVIPInfo(ByteBuffer _bb, VIPInfo obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public VIPInfo __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public int vipType() { int o = __offset(4); return o != 0 ? bb.get(o + bb_pos) & 0xFF : 0; }
  public boolean mutateVipType(int vip_type) { int o = __offset(4); if (o != 0) { bb.put(o + bb_pos, (byte)vip_type); return true; } else { return false; } }
  public long giftValueDaily() { int o = __offset(6); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0; }
  public boolean mutateGiftValueDaily(long gift_value_daily) { int o = __offset(6); if (o != 0) { bb.putInt(o + bb_pos, (int)gift_value_daily); return true; } else { return false; } }
  public long giftValueImme() { int o = __offset(8); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0; }
  public boolean mutateGiftValueImme(long gift_value_imme) { int o = __offset(8); if (o != 0) { bb.putInt(o + bb_pos, (int)gift_value_imme); return true; } else { return false; } }
  public long buyCoinPromo() { int o = __offset(10); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0; }
  public boolean mutateBuyCoinPromo(long buy_coin_promo) { int o = __offset(10); if (o != 0) { bb.putInt(o + bb_pos, (int)buy_coin_promo); return true; } else { return false; } }
  public int days() { int o = __offset(12); return o != 0 ? bb.get(o + bb_pos) & 0xFF : 0; }
  public boolean mutateDays(int days) { int o = __offset(12); if (o != 0) { bb.put(o + bb_pos, (byte)days); return true; } else { return false; } }
  public long shopId() { int o = __offset(14); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0; }
  public boolean mutateShopId(long shop_id) { int o = __offset(14); if (o != 0) { bb.putInt(o + bb_pos, (int)shop_id); return true; } else { return false; } }

  public static int createVIPInfo(FlatBufferBuilder builder,
      int vip_type,
      long gift_value_daily,
      long gift_value_imme,
      long buy_coin_promo,
      int days,
      long shop_id) {
    builder.startObject(6);
    VIPInfo.addShopId(builder, shop_id);
    VIPInfo.addBuyCoinPromo(builder, buy_coin_promo);
    VIPInfo.addGiftValueImme(builder, gift_value_imme);
    VIPInfo.addGiftValueDaily(builder, gift_value_daily);
    VIPInfo.addDays(builder, days);
    VIPInfo.addVipType(builder, vip_type);
    return VIPInfo.endVIPInfo(builder);
  }

  public static void startVIPInfo(FlatBufferBuilder builder) { builder.startObject(6); }
  public static void addVipType(FlatBufferBuilder builder, int vipType) { builder.addByte(0, (byte)vipType, 0); }
  public static void addGiftValueDaily(FlatBufferBuilder builder, long giftValueDaily) { builder.addInt(1, (int)giftValueDaily, 0); }
  public static void addGiftValueImme(FlatBufferBuilder builder, long giftValueImme) { builder.addInt(2, (int)giftValueImme, 0); }
  public static void addBuyCoinPromo(FlatBufferBuilder builder, long buyCoinPromo) { builder.addInt(3, (int)buyCoinPromo, 0); }
  public static void addDays(FlatBufferBuilder builder, int days) { builder.addByte(4, (byte)days, 0); }
  public static void addShopId(FlatBufferBuilder builder, long shopId) { builder.addInt(5, (int)shopId, 0); }
  public static int endVIPInfo(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

