// automatically generated by the FlatBuffers compiler, do not modify

package vn.com.vng.gsmobile.casino.flatbuffers;

public final class VipType {
  private VipType() { }
  public static final byte None = 0;
  public static final byte VIP1 = 1;
  public static final byte VIP2 = 2;
  public static final byte VIP3 = 3;
  public static final byte VIP4 = 4;
  public static final byte VIP5 = 5;

  public static final String[] names = { "None", "VIP1", "VIP2", "VIP3", "VIP4", "VIP5", };

  public static String name(int e) { return names[e]; }
}

