// automatically generated by the FlatBuffers compiler, do not modify

package vn.com.vng.gsmobile.casino.entries.tlmn;

public final class TrangType {
  private TrangType() { }
  public static final byte NONE = -1;
  public static final byte BA_DOI_THONG_3BICH = 0;
  public static final byte BON_DOI_THONG_3BICH = 1;
  public static final byte TU_QUY_3 = 2;
  public static final byte TU_QUY_2 = 3;
  public static final byte HAI_TU_QUY = 4;
  public static final byte SAU_DOI = 5;
  public static final byte NAM_DOI_THONG = 6;
  public static final byte SAU_DOI_THONG = 7;
  public static final byte DONG_HOA = 8;
  public static final byte SANH_RONG = 9;
  public static final byte SANH_RONG_DONG_HOA = 10;
  public static final byte BON_SAM_CO = 11;


  public static final String[] names = { "Card_None", "Ba_Doi_Thong_3Bich", "Bon_Doi_Thong_3Bich", "Tu_Quy_3", "Tu_Quy_2", "Hai_Tu_Quy", "Sau_Doi", "Nam_Doi_Thong", "Sau_Doi_Thong", "Dong_Hoa", "Sanh_Rong", "Sanh_Rong_Dong_Hoa", "Bon_Sam_Co"};

  public static String name(int e) { return names[e - NONE]; }
}

